#ifndef SE_INCL_DIRECTX12NATIVESHADERCATALOG_H
#define SE_INCL_DIRECTX12NATIVESHADERCATALOG_H
#ifdef PRAGMA_ONCE
#pragma once
#endif

#include <windows.h>
#include <d3d12.h>

enum DirectX12NativeShaderId
{
	DX12_SHADER_NATIVE_VALIDATION_VS,
	DX12_SHADER_NATIVE_VALIDATION_PS,
	DX12_SHADER_TEXTURED_2D_VS,
	DX12_SHADER_TEXTURED_2D_PS,
	DX12_SHADER_TEXTURED_ALPHA_TEST_2D_PS,
	DX12_SHADER_BLOOM_VS,
	DX12_SHADER_BLOOM_DOWNSAMPLE_PS,
	DX12_SHADER_BLOOM_BLUR_PS,
	DX12_SHADER_BLOOM_COMPOSITE_PS,
	DX12_SHADER_LEGACY_3D_VS,
	DX12_SHADER_LEGACY_3D_PS,
	DX12_SHADER_RIGID_LIT_3D_VS,
	DX12_SHADER_RIGID_LIT_3D_PS,
	DX12_SHADER_LEGACY_MATERIAL_3D_VS,
	DX12_SHADER_LEGACY_MATERIAL_3D_PS,
	DX12_SHADER_NATIVE_COUNT
};

// Devuelve un blob DXIL generado offline por DXC. El catálogo es la única
// frontera entre el pipeline nativo y el header mecánico producido en build.
bool GetDirectX12NativeShaderBytecode(
	DirectX12NativeShaderId shader,
	D3D12_SHADER_BYTECODE* pBytecode);

#endif
