#ifndef SE_INCL_DIRECTX12LEGACYSHADERFAMILY_H
#define SE_INCL_DIRECTX12LEGACYSHADERFAMILY_H
#ifdef PRAGMA_ONCE
#pragma once
#endif

#include <windows.h>

enum DirectX12LegacyVertexFamily
{
	DX12_LEGACY_VS_FIXED,
	DX12_LEGACY_VS_RIGID_LIT,
	DX12_LEGACY_VS_RIGID_LIT_PROJECTED,
	DX12_LEGACY_VS_RIGID_REFLECTED,
	DX12_LEGACY_VS_SKINNED_POSITION,
	DX12_LEGACY_VS_SKINNED_LIT,
	DX12_LEGACY_VS_SKINNED_LIT_DETAIL,
	DX12_LEGACY_VS_SKINNED_LIT_PROJECTED,
	DX12_LEGACY_VS_SKINNED_TANGENT,
	DX12_LEGACY_VS_SKINNED_TANGENT_PROJECTED,
	DX12_LEGACY_VS_RIGID_TANGENT,
	DX12_LEGACY_VS_RIGID_TANGENT_PROJECTED,
	DX12_LEGACY_VS_RIGID_LIT_REFLECTED,
	DX12_LEGACY_VS_PROJECTED_ONE,
	DX12_LEGACY_VS_PROJECTED_TWO,
	DX12_LEGACY_VS_PROJECTED_FOUR,
	DX12_LEGACY_VS_VERTEX_COLOR,
	DX12_LEGACY_VS_SKINNED_TANGENT_SPECULAR,
	DX12_LEGACY_VS_WATER,
	DX12_LEGACY_VS_UNKNOWN
};

enum DirectX12LegacyPixelFamily
{
	DX12_LEGACY_PS_FIXED,
	DX12_LEGACY_PS_BASE_ALPHA_INVERTED,
	DX12_LEGACY_PS_TERRAIN_FOUR_LAYER,
	DX12_LEGACY_PS_BLEND_TWO,
	DX12_LEGACY_PS_CONSTANT,
	DX12_LEGACY_PS_REFLECTION,
	DX12_LEGACY_PS_DETAIL,
	DX12_LEGACY_PS_ALPHA_MASK,
	DX12_LEGACY_PS_BASE_ALPHA_CONSTANT,
	DX12_LEGACY_PS_VERTEX_COLOR,
	DX12_LEGACY_PS_TEXTURE_ALPHA_SELECT,
	DX12_LEGACY_PS_TEXTURE_CONSTANT,
	DX12_LEGACY_PS_NORMAL_MAP,
	DX12_LEGACY_PS_LIT_BASE,
	DX12_LEGACY_PS_DETAIL_REFLECTION,
	DX12_LEGACY_PS_BASE_ALPHA_REFLECTION,
	DX12_LEGACY_PS_BASE_ALPHA_DETAIL,
	DX12_LEGACY_PS_NORMAL_MAP_REFLECTION,
	DX12_LEGACY_PS_NORMAL_MAP_REFLECTION_MASK,
	DX12_LEGACY_PS_NORMAL_MAP_SPECULAR,
	DX12_LEGACY_PS_WATER = 26,
	DX12_LEGACY_PS_UNKNOWN = 27
};

struct DirectX12LegacyShaderFamily
{
	DirectX12LegacyVertexFamily vertex;
	DirectX12LegacyPixelFamily pixel;
	bool nativeRigidPipeline;
	bool replacementValidated;
	bool requiresNormals;
	bool requiresWeights;
	bool requiresTangents;
	bool requiresSourceTexCoords;
	UINT textureCount;
};

bool GetDirectX12LegacyShaderFamily(
	UINT64 vertexFingerprint,
	UINT64 pixelFingerprint,
	UINT texturePassCount,
	DirectX12LegacyShaderFamily* pFamily);

#endif
