#include "stdh.h"

#include <Engine/Graphics/DirectX12NativeShaderSource.h>

const char* GetDirectX12NativeValidationShader()
{
	return
		"struct VSInput {\n"
		"  float3 position : POSITION;\n"
		"  float2 texCoord : TEXCOORD0;\n"
		"};\n"
		"struct VSOutput {\n"
		"  float4 position : SV_POSITION;\n"
		"  float2 texCoord : TEXCOORD0;\n"
		"};\n"
		"VSOutput VSMain(VSInput input) {\n"
		"  VSOutput output;\n"
		"  output.position = float4(input.position, 1.0f);\n"
		"  output.texCoord = input.texCoord;\n"
		"  return output;\n"
		"}\n"
		"Texture2D<float4> sourceTexture : register(t0);\n"
		"SamplerState sourceSampler : register(s0);\n"
		"float4 PSMain(VSOutput input) : SV_TARGET {\n"
		"  float3 sampledColor = sourceTexture.Sample(\n"
		"    sourceSampler, input.texCoord).rgb;\n"
		"  return float4(sampledColor, 0.0f);\n"
		"}\n";
}

const char* GetDirectX12Textured2DShader()
{
	return
		"struct VSInput {\n"
		"  float2 position : POSITION;\n"
		"  float2 texCoord : TEXCOORD0;\n"
		"  float4 color : COLOR0;\n"
		"};\n"
		"struct VSOutput {\n"
		"  float4 position : SV_POSITION;\n"
		"  float2 texCoord : TEXCOORD0;\n"
		"  float4 color : COLOR0;\n"
		"};\n"
		"VSOutput VSMain(VSInput input) {\n"
		"  VSOutput output;\n"
		"  output.position = float4(input.position, 0.0f, 1.0f);\n"
		"  output.texCoord = input.texCoord;\n"
		"  output.color = input.color;\n"
		"  return output;\n"
		"}\n"
		"Texture2D<float4> sourceTexture : register(t0);\n"
		"SamplerState sourceSampler : register(s0);\n"
		"float4 PSMain(VSOutput input) : SV_TARGET {\n"
		"  return sourceTexture.Sample(sourceSampler, input.texCoord)\n"
		"    * input.color;\n"
		"}\n";
}

const char* GetDirectX12TexturedAlphaTest2DShader()
{
	return
		"struct VSInput {\n"
		"  float2 position : POSITION;\n"
		"  float2 texCoord : TEXCOORD0;\n"
		"  float4 color : COLOR0;\n"
		"};\n"
		"struct VSOutput {\n"
		"  float4 position : SV_POSITION;\n"
		"  float2 texCoord : TEXCOORD0;\n"
		"  float4 color : COLOR0;\n"
		"};\n"
		"VSOutput VSMain(VSInput input) {\n"
		"  VSOutput output;\n"
		"  output.position = float4(input.position, 0.0f, 1.0f);\n"
		"  output.texCoord = input.texCoord;\n"
		"  output.color = input.color;\n"
		"  return output;\n"
		"}\n"
		"Texture2D<float4> sourceTexture : register(t0);\n"
		"SamplerState sourceSampler : register(s0);\n"
		"float4 PSMain(VSOutput input) : SV_TARGET {\n"
		"  float4 color = sourceTexture.Sample(\n"
		"    sourceSampler, input.texCoord) * input.color;\n"
		"  clip(color.a - (128.0f / 255.0f));\n"
		"  return color;\n"
		"}\n";
}

const char* GetDirectX12Legacy3DShader()
{
	return
		"struct VSInput {\n"
		"  float3 position : POSITION;\n"
		"  float2 texCoord : TEXCOORD0;\n"
		"  float4 color : COLOR0;\n"
		"};\n"
		"struct VSOutput {\n"
		"  float4 position : SV_POSITION;\n"
		"  float2 texCoord : TEXCOORD0;\n"
		"  float4 color : COLOR0;\n"
		"};\n"
		"VSOutput VSMain(VSInput input) {\n"
		"  VSOutput output;\n"
		"  output.position = float4(input.position, 1.0f);\n"
		"  output.texCoord = input.texCoord;\n"
		"  output.color = input.color;\n"
		"  return output;\n"
		"}\n"
		"Texture2D<float4> sourceTexture : register(t0);\n"
		"SamplerState sourceSampler : register(s0);\n"
		"float4 PSMain(VSOutput input) : SV_TARGET {\n"
		"  return sourceTexture.Sample(sourceSampler, input.texCoord)\n"
		"    * input.color;\n"
		"}\n";
}

const char* GetDirectX12RigidLit3DShader()
{
	return
		"cbuffer LegacyConstants : register(b0) {\n"
		"  float4 constants[13];\n"
		"};\n"
		"cbuffer LegacyPixelConstants : register(b1) {\n"
		"  float4 pixelConstant0;\n"
		"  float3 pixelConstant1;\n"
		"};\n"
		"struct VSInput {\n"
		"  float3 position : POSITION;\n"
		"  float2 texCoord : TEXCOORD0;\n"
		"  float4 color : COLOR0;\n"
		"  float3 normal : NORMAL0;\n"
		"};\n"
		"struct VSOutput {\n"
		"  float4 position : SV_POSITION;\n"
		"  float2 texCoord0 : TEXCOORD0;\n"
		"  float2 texCoord1 : TEXCOORD1;\n"
		"  float4 color : COLOR0;\n"
		"};\n"
		"VSOutput VSMain(VSInput input) {\n"
		"  VSOutput output;\n"
		"  float4 p = float4(input.position, 1.0f);\n"
		"  output.position = float4(dot(p, constants[0]),\n"
		"    dot(p, constants[1]), dot(p, constants[2]),\n"
		"    dot(p, constants[3]));\n"
		"  float3 n = normalize(input.normal);\n"
		"  float lighting = clamp(dot(n, constants[4].xyz),\n"
		"    constants[7].x, constants[7].y);\n"
		"  output.color = float4(constants[5].xyz * lighting\n"
		"    + constants[6].xyz, constants[7].y) * constants[7].y;\n"
		"  output.texCoord0 = input.texCoord;\n"
		"  output.texCoord1 = input.texCoord * constants[12].xy;\n"
		"  return output;\n"
		"}\n"
		"Texture2D<float4> sourceTexture : register(t0);\n"
		"Texture2D<float4> detailTexture : register(t1);\n"
		"SamplerState sourceSampler : register(s0);\n"
		"float4 PSMain(VSOutput input) : SV_TARGET {\n"
		"  float4 base = sourceTexture.Sample(\n"
		"    sourceSampler, input.texCoord0) * pixelConstant0;\n"
		"  float4 detail = detailTexture.Sample(\n"
		"    sourceSampler, input.texCoord1)\n"
		"    * float4(pixelConstant1, 1.0f);\n"
		"  return base * detail * input.color * 4.0f;\n"
		"}\n";
}

const char* GetDirectX12LegacyMaterial3DShader()
{
	return
		"cbuffer LegacyConstants : register(b0) {\n"
		"  float4 constants[13];\n"
		"};\n"
		"cbuffer MaterialState : register(b1) {\n"
		"  float4 materialState0;\n"
		"};\n"
		"struct VSInput {\n"
		"  float3 position : POSITION;\n"
		"  float2 texCoord0 : TEXCOORD0;\n"
		"  float4 color0 : COLOR0;\n"
		"  float3 normal : NORMAL0;\n"
		"  float2 texCoord1 : TEXCOORD1;\n"
		"  float2 texCoord2 : TEXCOORD2;\n"
		"  float2 texCoord3 : TEXCOORD3;\n"
		"  float4 tangent : TANGENT0;\n"
		"  float4 blendIndices : BLENDINDICES0;\n"
		"  float4 blendWeights : BLENDWEIGHT0;\n"
		"  float4 color1 : COLOR1;\n"
		"  float clipW : TEXCOORD13;\n"
		"};\n"
		"struct VSOutput {\n"
		"  float4 position : SV_POSITION;\n"
		"  float2 texCoord0 : TEXCOORD0;\n"
		"  float2 texCoord1 : TEXCOORD1;\n"
		"  float2 texCoord2 : TEXCOORD2;\n"
		"  float2 texCoord3 : TEXCOORD3;\n"
		"  float4 color0 : COLOR0;\n"
		"  float4 color1 : COLOR1;\n"
		"};\n"
		"VSOutput VSMain(VSInput input) {\n"
		"  VSOutput output;\n"
		"  float w = input.clipW;\n"
		"  output.position = float4(input.position * w, w);\n"
		"  output.texCoord0 = input.texCoord0;\n"
		"  output.texCoord1 = input.texCoord1;\n"
		"  output.texCoord2 = input.texCoord2;\n"
		"  output.texCoord3 = input.texCoord3;\n"
		"  output.color0 = input.color0;\n"
		"  output.color1 = input.color1;\n"
		"  return output;\n"
		"}\n"
		"Texture2D<float4> texture0 : register(t0);\n"
		"Texture2D<float4> texture1 : register(t1);\n"
		"Texture2D<float4> texture2 : register(t2);\n"
		"Texture2D<float4> texture3 : register(t3);\n"
		"SamplerState sourceSampler : register(s0);\n"
		"float4 ResolveFixedArgument(int encoded, float4 textureValue,\n"
		"  float4 diffuse, float4 current, float4 temporary,\n"
		"  float4 textureFactor, float4 stageConstant) {\n"
		"  int selector = encoded & 15;\n"
		"  float4 value = selector == 0 ? diffuse\n"
		"    : selector == 1 ? current\n"
		"    : selector == 2 ? textureValue\n"
		"    : selector == 3 ? textureFactor\n"
		"    : selector == 4 ? float4(0,0,0,0)\n"
		"    : selector == 5 ? temporary\n"
		"    : stageConstant;\n"
		"  if ((encoded & 16) != 0) value = 1.0f - value;\n"
		"  if ((encoded & 32) != 0) value = value.aaaa;\n"
		"  return value;\n"
		"}\n"
		"float4 ApplyFixedOperation(int operation, float4 argument1,\n"
		"  float4 argument2, float4 diffuse, float4 current,\n"
		"  float4 textureValue, float4 textureFactor) {\n"
		"  if (operation == 2) return argument1;\n"
		"  if (operation == 3) return argument2;\n"
		"  if (operation == 4) return argument1 * argument2;\n"
		"  if (operation == 5) return argument1 * argument2 * 2.0f;\n"
		"  if (operation == 6) return argument1 * argument2 * 4.0f;\n"
		"  if (operation == 7) return argument1 + argument2;\n"
		"  if (operation == 8) return argument1 + argument2 - 0.5f;\n"
		"  if (operation == 9)\n"
		"    return (argument1 + argument2 - 0.5f) * 2.0f;\n"
		"  if (operation == 10) return argument1 - argument2;\n"
		"  if (operation == 11)\n"
		"    return argument1 + argument2 - argument1 * argument2;\n"
		"  if (operation == 12)\n"
		"    return lerp(argument2, argument1, diffuse.a);\n"
		"  if (operation == 13)\n"
		"    return lerp(argument2, argument1, textureValue.a);\n"
		"  if (operation == 14)\n"
		"    return lerp(argument2, argument1, textureFactor.a);\n"
		"  if (operation == 15)\n"
		"    return argument1 + argument2 * (1.0f - textureValue.a);\n"
		"  if (operation == 16)\n"
		"    return lerp(argument2, argument1, current.a);\n"
		"  if (operation == 18)\n"
		"    return argument1 + argument2 * argument1.a;\n"
		"  if (operation == 19)\n"
		"    return argument1 * argument2 + argument1.a;\n"
		"  if (operation == 20)\n"
		"    return argument1 + argument2 * (1.0f - argument1.a);\n"
		"  if (operation == 21)\n"
		"    return argument1.a + argument2 * (1.0f - argument1);\n"
		"  if (operation == 24) {\n"
		"    float value = dot(argument1.rgb * 2.0f - 1.0f,\n"
		"      argument2.rgb * 2.0f - 1.0f);\n"
		"    return float4(value, value, value, value);\n"
		"  }\n"
		"  return current;\n"
		"}\n"
		"float4 PSMain(VSOutput input) : SV_TARGET {\n"
		"  const int mode = (int)(materialState0.x + 0.5f);\n"
		"  float4 s0 = texture0.Sample(sourceSampler, input.texCoord0);\n"
		"  float4 s1 = texture1.Sample(sourceSampler, input.texCoord1);\n"
		"  float4 s2 = texture2.Sample(sourceSampler, input.texCoord2);\n"
		"  float4 s3 = texture3.Sample(sourceSampler, input.texCoord3);\n"
		"  if (mode == 0) {\n"
		"    int passes = (int)(materialState0.y + 0.5f);\n"
		"    float4 current = input.color0;\n"
		"    float4 temporary = current;\n"
		"    [unroll] for (int stage = 0; stage < 4; ++stage) {\n"
		"      if (stage >= passes) break;\n"
		"      float4 textureValue = stage == 0 ? s0\n"
		"        : stage == 1 ? s1 : stage == 2 ? s2 : s3;\n"
		"      int baseConstant = stage * 3;\n"
		"      int colorOperation =\n"
		"        (int)(constants[baseConstant].x + 0.5f);\n"
		"      if (colorOperation == 1) break;\n"
		"      int colorArgument1 =\n"
		"        (int)(constants[baseConstant].y + 0.5f);\n"
		"      int colorArgument2 =\n"
		"        (int)(constants[baseConstant].z + 0.5f);\n"
		"      int alphaOperation =\n"
		"        (int)(constants[baseConstant].w + 0.5f);\n"
		"      int alphaArgument1 =\n"
		"        (int)(constants[baseConstant + 1].x + 0.5f);\n"
		"      int alphaArgument2 =\n"
		"        (int)(constants[baseConstant + 1].y + 0.5f);\n"
		"      int resultArgument =\n"
		"        (int)(constants[baseConstant + 1].z + 0.5f);\n"
		"      float4 stageConstant = constants[baseConstant + 2];\n"
		"      if (colorOperation == 1) break;\n"
		"      float4 color1 = ResolveFixedArgument(colorArgument1,\n"
		"        textureValue, input.color0, current, temporary,\n"
		"        constants[12], stageConstant);\n"
		"      float4 color2 = ResolveFixedArgument(colorArgument2,\n"
		"        textureValue, input.color0, current, temporary,\n"
		"        constants[12], stageConstant);\n"
		"      float4 result = ApplyFixedOperation(colorOperation,\n"
		"        color1, color2, input.color0, current,\n"
		"        textureValue, constants[12]);\n"
		"      if (alphaOperation != 1) {\n"
		"        float4 alpha1 = ResolveFixedArgument(alphaArgument1,\n"
		"          textureValue, input.color0, current, temporary,\n"
		"          constants[12], stageConstant);\n"
		"        float4 alpha2 = ResolveFixedArgument(alphaArgument2,\n"
		"          textureValue, input.color0, current, temporary,\n"
		"          constants[12], stageConstant);\n"
		"        result.a = ApplyFixedOperation(alphaOperation,\n"
		"          alpha1, alpha2, input.color0, current,\n"
		"          textureValue, constants[12]).a;\n"
		"      }\n"
		"      if ((resultArgument & 15) == 5) temporary = result;\n"
		"      else current = result;\n"
		"    }\n"
		"    if (materialState0.z > 0.5f)\n"
		"      clip(current.a - materialState0.w);\n"
		"    return saturate(current);\n"
		"  }\n"
		"  if (materialState0.z > 0.5f)\n"
		"    clip(s0.a - materialState0.w);\n"
		"  if (mode == 1) {\n"
		"    float4 c = s0 * constants[0];\n"
		"    return float4(c.rgb * c.a * input.color0.rgb * 2.0f,\n"
		"      1.0f - c.a);\n"
		"  }\n"
		"  if (mode == 2) {\n"
		"    float baseAlpha = s0.a * s1.a;\n"
		"    float blendAlpha = s2.a * s3.a;\n"
		"    return float4(lerp(s2.rgb, s0.rgb * baseAlpha,\n"
		"      1.0f - blendAlpha), (1.0f - baseAlpha) *\n"
		"      (1.0f - blendAlpha));\n"
		"  }\n"
		"  if (mode == 3)\n"
		"    return lerp(s1, s0, constants[7]) * constants[6];\n"
		"  if (mode == 4)\n"
		"    return constants[0] * constants[1];\n"
		"  if (mode == 5) {\n"
		"    float4 lit = saturate(s0 * input.color0 * float4(2,2,2,1));\n"
		"    float4 reflection = s2 * constants[7];\n"
		"    return float4(lerp(lit.rgb, reflection.rgb,\n"
		"      reflection.a), lit.a);\n"
		"  }\n"
		"  if (mode == 6)\n"
		"    return s0 * constants[0] * s1 * constants[1]\n"
		"      * input.color0 * 4.0f;\n"
		"  if (mode == 7) {\n"
		"    float alpha = s0.a * s1.a;\n"
		"    return float4(s0.rgb * alpha, 1.0f - alpha);\n"
		"  }\n"
		"  if (mode == 8) {\n"
		"    float4 c = s0 * constants[0];\n"
		"    return float4(c.rgb * c.a * input.color0.rgb * 2.0f,\n"
		"      constants[1].x);\n"
		"  }\n"
		"  if (mode == 9)\n"
		"    return s0 * input.color0;\n"
		"  if (mode == 10) {\n"
		"    float a = s0.a + constants[2].a;\n"
		"    return float4(constants[0].rgb,\n"
		"      a >= 0.5f ? constants[0].a : constants[1].a);\n"
		"  }\n"
		"  if (mode == 11)\n"
		"    return s0 * constants[7];\n"
		"  if (mode == 12) {\n"
		"    float light = saturate(dot(s0.rgb * 2.0f - 1.0f,\n"
		"      input.color1.rgb * 2.0f - 1.0f));\n"
		"    float3 lighting = saturate(light * input.color0.rgb\n"
		"      + constants[0].rgb);\n"
		"    return float4(saturate(s1.rgb * lighting * 2.0f),\n"
		"      s1.a * input.color0.a);\n"
		"  }\n"
		"  if (mode == 13)\n"
		"    return saturate(s0 * input.color0 * float4(2,2,2,1));\n"
		"  if (mode == 14) {\n"
		"    float4 detailed = s0 * constants[0] * s1\n"
		"      * constants[1] * input.color0 * 4.0f;\n"
		"    float4 reflection = s2 * constants[7];\n"
		"    return float4(lerp(detailed.rgb, reflection.rgb,\n"
		"      reflection.a), detailed.a);\n"
		"  }\n"
		"  if (mode == 15) {\n"
		"    float4 base = s0 * constants[0];\n"
		"    float4 reflection = s2 * constants[7];\n"
		"    float alpha = base.a * (1.0f - reflection.a);\n"
		"    return float4(base.rgb * alpha * input.color0.rgb * 2.0f,\n"
		"      1.0f - alpha);\n"
		"  }\n"
		"  if (mode == 16) {\n"
		"    float4 base = s0 * constants[0];\n"
		"    float4 detail = s1 * constants[7];\n"
		"    float alpha = base.a * (1.0f - detail.a);\n"
		"    return float4(base.rgb * alpha * input.color0.rgb * 2.0f,\n"
		"      1.0f - alpha);\n"
		"  }\n"
		"  if (mode == 17) {\n"
		"    float light = saturate(dot(s0.rgb * 2.0f - 1.0f,\n"
		"      input.color1.rgb * 2.0f - 1.0f));\n"
		"    float3 lighting = saturate(light * input.color0.rgb\n"
		"      + constants[0].rgb);\n"
		"    float4 base = float4(saturate(s1.rgb * lighting * 2.0f),\n"
		"      s1.a * input.color0.a);\n"
		"    float4 reflection = s2 * constants[7];\n"
		"    return float4(lerp(base.rgb, reflection.rgb,\n"
		"      reflection.a), base.a);\n"
		"  }\n"
		"  if (mode == 18) {\n"
		"    float light = saturate(dot(s0.rgb * 2.0f - 1.0f,\n"
		"      input.color1.rgb * 2.0f - 1.0f));\n"
		"    float3 lighting = saturate(light * input.color0.rgb\n"
		"      + constants[0].rgb);\n"
		"    float4 reflection = s2 * constants[7];\n"
		"    return float4(saturate(s1.rgb * lighting * 2.0f),\n"
		"      s1.a * input.color0.a * (1.0f - reflection.a));\n"
		"  }\n"
		"  if (mode == 19) {\n"
		"    float light = saturate(dot(s0.rgb * 2.0f - 1.0f,\n"
		"      input.color1.rgb * 2.0f - 1.0f));\n"
		"    float3 lighting = saturate(light * input.color0.rgb\n"
		"      + constants[0].rgb);\n"
		"    float specular = s0.a * input.color1.a;\n"
		"    return float4(saturate(s1.rgb * lighting * 2.0f\n"
		"      + specular), s1.a * input.color0.a);\n"
		"  }\n"
		"  if (mode == 20) return float4(s0.rgb, 1.0f);\n"
		"  if (mode == 21) return float4(s1.rgb, 1.0f);\n"
		"  if (mode == 22) return float4(s2.rgb, 1.0f);\n"
		"  if (mode == 23) return float4(s3.rgb, 1.0f);\n"
		"  if (mode == 24) return float4(s0.a, s1.a, s2.a, 1.0f);\n"
		"  if (mode == 25) return float4(s3.aaa, 1.0f);\n"
		"  int passes = (int)(materialState0.y + 0.5f);\n"
		"  float4 fixedColor = input.color0;\n"
		"  if (passes > 0) fixedColor *= s0;\n"
		"  if (passes > 1) fixedColor *= s1;\n"
		"  if (passes > 2) fixedColor *= s2;\n"
		"  if (passes > 3) fixedColor *= s3;\n"
		"  return fixedColor;\n"
		"}\n";
}
