/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"

#include "StdH.h"
#include <EntitiesMP/AnimationHub.h>

#include <AnimationChanger.h>
#include <AnimationChanger_tables.h>
CEntityEvent *EChangeAnim::MakeCopy(void) { 	CEntityEvent *peeCopy = new EChangeAnim(*this); 	return peeCopy;}
SLONG EChangeAnim::GetSizeOf(void) { 	return sizeof(*this);}
EChangeAnim::EChangeAnim() : CEntityEvent(EVENTCODE_EChangeAnim) {
	ClearToDefault(iModelAnim);
	ClearToDefault(bModelLoop);
	ClearToDefault(iTextureAnim);
	ClearToDefault(bTextureLoop);
	ClearToDefault(iLightAnim);
	ClearToDefault(iAmbientLightAnim);
	ClearToDefault(bLightLoop);
	ClearToDefault(bAmbientLightLoop);
	ClearToDefault(colAmbient);
	ClearToDefault(colDiffuse);
	ClearToDefault(strAnimation);
	ClearToDefault(fBlendTime);
	ClearToDefault(AnimType);
}
BOOL EChangeAnim::CheckIDs(void) {	return TRUE ; }

void CAnimationChanger::SetDefaultProperties(void) {
	m_strName = "Animation changer";
	m_strDescription = "";
	m_penTarget = NULL;
	m_iModelAnim = 0;
	m_bModelLoop = FALSE ;
	m_iTextureAnim = 0;
	m_bTextureLoop = FALSE ;
	m_iLightAnim = 0;
	m_bLightLoop = FALSE ;
	m_iAmbientLightAnim = 0;
	m_bAmbientLightLoop = FALSE ;
	m_colAmbient = C_dBLUE ;
	m_colDiffuse = C_GRAY ;
	m_strModelAnim = "";
	m_fBlendTime = 0.05f;
	CRationalEntity::SetDefaultProperties();
}

#line 64 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
const CTString & CAnimationChanger::GetDescription(void)const {
#line 65 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
((CTString &) m_strDescription ) . PrintF  ("-><none>");
#line 66 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
if(m_penTarget  != NULL ){
#line 67 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
((CTString &) m_strDescription ) . PrintF  ("->%s" , m_penTarget  -> GetName  ());
#line 68 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
}
#line 69 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
return m_strDescription ;
#line 70 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
}

#line 73 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
CAnimData * CAnimationChanger::GetAnimData(SLONG slPropertyOffset) 
#line 74 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
{
#line 75 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
CEntity  * penTarget  = m_penTarget ;
#line 77 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
if(penTarget  == NULL ){
#line 78 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
return NULL ;
#line 79 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
}
#line 81 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
if(IsOfClass  (penTarget  , "AnimationHub")){
#line 82 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
penTarget  = ((CAnimationHub  *) penTarget ) -> m_penTarget0 ;
#line 83 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
}
#line 85 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
if(penTarget  == NULL ){
#line 86 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
return NULL ;
#line 87 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
}
#line 90 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
if(IsOfClass  (penTarget  , "ModelHolder2")){
#line 91 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
CModelHolder2  * penModel  = (CModelHolder2  *) & * penTarget ;
#line 92 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
if(slPropertyOffset  == offsetof  (CAnimationChanger  , m_iModelAnim )){
#line 93 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
return penModel  -> GetModelObject  () -> GetData  ();
#line 94 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
}else if(slPropertyOffset  == offsetof  (CAnimationChanger  , m_iTextureAnim )){
#line 95 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
return penModel  -> GetModelObject  () -> mo_toTexture  . GetData  ();
#line 96 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
}else if(slPropertyOffset  == offsetof  (CAnimationChanger  , m_iLightAnim )){
#line 97 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
return penModel  -> m_aoLightAnimation  . GetData  ();
#line 98 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
}
#line 101 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
}else if(IsOfClass  (penTarget  , "Light")){
#line 102 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
CLight  * penLight  = (CLight  *) & * penTarget ;
#line 104 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
if(slPropertyOffset  == offsetof  (CAnimationChanger  , m_iLightAnim ))
#line 105 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
{
#line 106 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
return penLight  -> m_aoLightAnimation  . GetData  ();
#line 107 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
}
#line 108 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
else if(slPropertyOffset  == offsetof  (CAnimationChanger  , m_iAmbientLightAnim ))
#line 109 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
{
#line 110 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
return penLight  -> m_aoAmbientLightAnimation  . GetData  ();
#line 111 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
}
#line 112 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
}
#line 114 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
return CEntity  :: GetAnimData  (slPropertyOffset );
#line 115 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
}
BOOL CAnimationChanger::
#line 118 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CAnimationChanger_Main
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CAnimationChanger::Main expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 120 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
InitAsEditorModel  ();
#line 121 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 122 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 125 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
SetModel  (MODEL_CHANGER );
#line 126 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
SetModelMainTexture  (TEXTURE_CHANGER );
#line 129 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
if(m_penTarget  != NULL  && 
#line 130 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
! IsOfClass  (m_penTarget  , "AnimationHub") && 
#line 131 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
! IsOfClass  (m_penTarget  , "ModelHolder2") && 
#line 132 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
! IsOfClass  (m_penTarget  , "Light")){
#line 133 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
WarningMessage  ("Target must be AnimationHub ModelHolder2 or Light!");
#line 134 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
m_penTarget  = NULL ;
#line 135 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
}
#line 136 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
if(m_penTarget  == NULL ){
#line 137 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
Return(STATE_CURRENT,EVoid());
#line 137 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
return TRUE;
#line 138 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
}
#line 141 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x00da0001, FALSE, EBegin());return TRUE;}BOOL CAnimationChanger::H0x00da0001_Main_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x00da0001
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_EStart):{const EStart&e= (EStart&)__eeInput;

#line 144 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
EChangeAnim  eChange ;
#line 145 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
eChange  . iModelAnim  = m_iModelAnim ;
#line 146 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
eChange  . iTextureAnim  = m_iTextureAnim ;
#line 147 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
eChange  . iLightAnim  = m_iLightAnim ;
#line 148 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
eChange  . iAmbientLightAnim  = m_iAmbientLightAnim ;
#line 149 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
eChange  . bModelLoop  = m_bModelLoop ;
#line 150 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
eChange  . bTextureLoop  = m_bTextureLoop ;
#line 151 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
eChange  . bLightLoop  = m_bLightLoop ;
#line 152 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
eChange  . colAmbient  = m_colAmbient ;
#line 153 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
eChange  . colDiffuse  = m_colDiffuse ;
#line 154 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
eChange  . strAnimation  = m_strModelAnim ;
#line 155 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
eChange  . fBlendTime  = m_fBlendTime ;
#line 156 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
m_penTarget  -> SendEvent  (eChange  , TRUE );
#line 157 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
return TRUE;
#line 158 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
}ASSERT(FALSE);break;default: return FALSE; break;
#line 159 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
}return TRUE;}BOOL CAnimationChanger::H0x00da0002_Main_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x00da0002

#line 160 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
Return(STATE_CURRENT,EVoid());
#line 160 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AnimationChanger.es"
return TRUE; ASSERT(FALSE); return TRUE;};