/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AreaMarker.es"

#include "StdH.h"

#include <AreaMarker.h>
#include <AreaMarker_tables.h>
void CAreaMarker::SetDefaultProperties(void) {
	m_strName = "AreaMarker";
	m_strDescription = "";
	m_boxArea = FLOATaabbox3D(FLOAT3D (0 , 0 , 0) , FLOAT3D (10 , 10 , 10));
	CEntity::SetDefaultProperties();
}

#line 22 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AreaMarker.es"
void CAreaMarker::GetAreaBox(FLOATaabbox3D & box) {
#line 23 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AreaMarker.es"
box  = m_boxArea ;
#line 24 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AreaMarker.es"
box  += GetPlacement  () . pl_PositionVector ;
#line 25 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AreaMarker.es"
return ;
#line 26 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AreaMarker.es"
}
BOOL CAreaMarker::
#line 29 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AreaMarker.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CAreaMarker_Main
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CAreaMarker::Main expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 31 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AreaMarker.es"
InitAsEditorModel  ();
#line 32 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AreaMarker.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 33 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AreaMarker.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 36 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AreaMarker.es"
SetModel  (MODEL_AREAMARKER );
#line 37 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AreaMarker.es"
SetModelMainTexture  (TEXTURE_AREAMARKER );
#line 39 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AreaMarker.es"
Return(STATE_CURRENT,EVoid());
#line 39 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/AreaMarker.es"
return TRUE; ASSERT(FALSE); return TRUE;};