/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"

#include "StdH.h"

#include <Debris.h>
#include <Debris_tables.h>
CEntityEvent *ESpawnDebris::MakeCopy(void) { 	CEntityEvent *peeCopy = new ESpawnDebris(*this); 	return peeCopy;}
SLONG ESpawnDebris::GetSizeOf(void) { 	return sizeof(*this);}
ESpawnDebris::ESpawnDebris() : CEntityEvent(EVENTCODE_ESpawnDebris) {
	ClearToDefault(Eeibt);
	ClearToDefault(pmd);
	ClearToDefault(fSize);
	ClearToDefault(ptd);
	ClearToDefault(ptdRefl);
	ClearToDefault(ptdSpec);
	ClearToDefault(ptdBump);
	ClearToDefault(iModelAnim);
	ClearToDefault(dptParticles);
	ClearToDefault(betStain);
	ClearToDefault(colDebris);
	ClearToDefault(bCustomShading);
	ClearToDefault(aShadingDirection);
	ClearToDefault(colCustomAmbient);
	ClearToDefault(colCustomDiffuse);
	ClearToDefault(bImmaterialASAP);
	ClearToDefault(fDustStretch);
	ClearToDefault(vStretch);
	ClearToDefault(penFallFXPapa);
}
BOOL ESpawnDebris::CheckIDs(void) {	return TRUE ; }

#line 40 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"


void CDebris::SetDefaultProperties(void) {
	m_dptParticles = DPT_NONE ;
	m_iBodyType = 0;
	m_bFade = FALSE ;
	m_fFadeStartTime = 0.0f;
	m_fFadeTime = 0.0f;
	m_fLastStainHitPoint = FLOAT3D(0 , 0 , 0);
	m_betStain = BET_NONE ;
	m_ctLeftStains = 0;
	m_tmStarted = 0.0f;
	m_fStretch = 1.0f;
	m_aShadingDirection = ANGLE3D(0 , 0 , 0);
	m_bCustomShading = FALSE ;
	m_colCustomAmbient = COLOR(C_WHITE  | CT_OPAQUE );
	m_colCustomDiffuse = COLOR(C_WHITE  | CT_OPAQUE );
	m_bImmaterialASAP = FALSE ;
	m_fDustStretch = 0.0f;
	m_bTouchedGround = FALSE ;
	m_penFallFXPapa = NULL;
	m_bDebrisFade = TRUE ;
	m_bDebrisCollision = FALSE ;
	CMovableModelEntity::SetDefaultProperties();
}

#line 81 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
void * CDebris::GetEntityInfo(void) {
#line 82 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
return GetStdEntityInfo  ((EntityInfoBodyType ) m_iBodyType );
#line 83 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}

#line 86 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
void CDebris::ReceiveDamage(CEntity * penInflictor,enum DamageType dmtType,
#line 87 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
FLOAT fDamageAmmount,const FLOAT3D & vHitPoint,const FLOAT3D & vDirection) 
#line 88 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{
#line 90 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if((_pTimer  -> CurrentTick  () - m_tmStarted  < 1.0f) && (_pTimer  -> CurrentTick  () - m_tmStarted  < 5.0f)){
#line 91 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
return ;
#line 92 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 93 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
CMovableModelEntity  :: ReceiveDamage  (penInflictor  , dmtType  , fDamageAmmount  , vHitPoint  , vDirection );
#line 94 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}

#line 100 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
BOOL CDebris::AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient) 
#line 101 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{
#line 102 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if(m_bCustomShading )
#line 103 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{
#line 104 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
colLight  = m_colCustomDiffuse ;
#line 105 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
colAmbient  = m_colCustomAmbient ;
#line 106 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
AnglesToDirectionVector  (m_aShadingDirection  , vLightDirection );
#line 107 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
vLightDirection  = - vLightDirection ;
#line 108 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 110 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if(m_bFade ){
#line 111 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
FLOAT fTimeRemain  = m_fFadeStartTime  + m_fFadeTime  - _pTimer  -> CurrentTick  ();
#line 112 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if(fTimeRemain  < 0.0f){fTimeRemain  = 0.0f;}
#line 113 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
COLOR colAlpha  = GetModelObject  () -> mo_colBlendColor ;
#line 114 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
colAlpha  = (colAlpha  & 0xffffff00) + (COLOR (fTimeRemain  / m_fFadeTime  * 0xff) & 0xff);
#line 115 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
GetModelObject  () -> mo_colBlendColor  = colAlpha ;
#line 116 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 118 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
return FALSE ;
#line 119 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}

#line 128 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
void CDebris::LeaveStain(void) 
#line 129 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{
#line 131 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if(m_betStain  == BET_NONE ){
#line 133 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
return ;
#line 134 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 137 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if(m_ctLeftStains  > 5){
#line 138 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
return ;
#line 139 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 140 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
ESpawnEffect  ese ;
#line 141 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
FLOAT3D vPoint ;
#line 142 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
FLOATplane3D plPlaneNormal ;
#line 143 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
FLOAT fDistanceToEdge ;
#line 146 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if(GetNearestPolygon  (vPoint  , plPlaneNormal  , fDistanceToEdge )){
#line 148 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if((m_fLastStainHitPoint  - vPoint ) . Length  () > 3.0f && 
#line 149 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
(vPoint  - GetPlacement  () . pl_PositionVector ) . Length  () < 3.5f){
#line 150 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_fLastStainHitPoint  = vPoint ;
#line 152 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
ese  . colMuliplier  = C_WHITE  | CT_OPAQUE ;
#line 153 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
ese  . betType  = m_betStain ;
#line 154 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
ese  . vNormal  = FLOAT3D (plPlaneNormal );
#line 155 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
GetNormalComponent  (en_vCurrentTranslationAbsolute  , plPlaneNormal  , ese  . vDirection );
#line 156 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
FLOAT fLength  = ese  . vDirection  . Length  () / 7.5f;
#line 157 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
fLength  = Clamp  (fLength  , 1.0f , 15.0f);
#line 158 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
ese  . vStretch  = FLOAT3D (1.0f , fLength  * 1.0f , 1.0f);
#line 159 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
SpawnEffect  (CPlacement3D (vPoint  + ese  . vNormal  / 50.0f * (FRnd  () + 0.5f) , ANGLE3D (0 , 0 , 0)) , ese );
#line 160 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_ctLeftStains  ++;
#line 161 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 162 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 163 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}

#line 166 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
void CDebris::SpawnEffect(const CPlacement3D & plEffect,const class ESpawnEffect & eSpawnEffect) 
#line 167 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{
#line 168 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
CEntityPointer penEffect  = CreateEntity  (plEffect  , CLASS_BASIC_EFFECT  , WLD_AUTO_ENTITY_ID  , FALSE );
#line 169 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
penEffect  -> Initialize  (eSpawnEffect  , FALSE );
#line 170 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}

#line 173 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
void CDebris::RenderParticles(void) 
#line 174 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{
#line 176 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if(en_vCurrentTranslationAbsolute  . Length  () < 0.1f){
#line 178 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
return ;
#line 179 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 180 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
switch(m_dptParticles ){
#line 181 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
case DPT_BLOODTRAIL : {
#line 182 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
Particles_BloodTrail  (this );
#line 183 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}break ;
#line 184 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
case DPR_SMOKETRAIL : {
#line 185 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
Particles_GrenadeTrail  (this );
#line 186 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}break ;
#line 187 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
case DPR_SPARKS : {
#line 188 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
Particles_ColoredStarsTrail  (this );
#line 189 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}break ;
#line 190 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
case DPR_FLYINGTRAIL : {
#line 192 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
Particles_BombTrail  (this );
#line 193 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}break ;
#line 194 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
case DPT_AFTERBURNER : {
#line 195 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
Particles_AfterBurner  (this  , m_tmStarted  , 0.5f);
#line 196 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}break ;
#line 197 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
default  : ASSERT  (FALSE );
#line 198 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
case DPT_NONE : 
#line 199 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
return ;
#line 200 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 201 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}

#line 204 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
void CDebris::Explode(void) 
#line 205 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{
#line 207 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
CPlacement3D plExplosion  = GetPlacement  ();
#line 208 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
CEntityPointer penExplosion  = CreateEntity  (plExplosion  , CLASS_BASIC_EFFECT  , WLD_AUTO_ENTITY_ID  , FALSE );
#line 209 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
ESpawnEffect  eSpawnEffect ;
#line 210 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
eSpawnEffect  . colMuliplier  = C_WHITE  | CT_OPAQUE ;
#line 211 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
eSpawnEffect  . betType  = BET_BOMB ;
#line 212 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
eSpawnEffect  . vStretch  = FLOAT3D (0.3f , 0.3f , 0.3f);
#line 213 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
penExplosion  -> Initialize  (eSpawnEffect  , FALSE );
#line 214 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
BOOL CDebris::
#line 222 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CDebris_Main
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_ESpawnDebris, "CDebris::Main expects 'ESpawnDebris' as input!");	const ESpawnDebris &eSpawn = (const ESpawnDebris &)__eeInput;
#line 224 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
InitAsModel  ();
#line 225 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
SetPhysicsFlags  (EPF_MODEL_BOUNCING  | EPF_CANFADESPINNING );
#line 226 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
SetCollisionFlags  (ECF_DEBRIS );
#line 227 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
SetFlags  (GetFlags  () | ENF_SEETHROUGH );
#line 228 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
SetHealth  (25.0f);
#line 229 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
SetFlagOn  (ENF_CLIENTHANDLING );
#line 230 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
SetFlagOff  (ENF_PROPSCHANGED );
#line 231 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
en_fBounceDampNormal  = 0.15f;
#line 232 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
en_fBounceDampParallel  = 0.5f;
#line 233 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
en_fJumpControlMultiplier  = 0.0f;
#line 236 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if(eSpawn  . Eeibt  == EIBT_ICE ){
#line 237 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
en_fDensity  = 500.0f;
#line 238 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}else if(eSpawn  . Eeibt  == EIBT_WOOD ){
#line 239 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
en_fDensity  = 500.0f;
#line 240 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}else if(eSpawn  . Eeibt  == EIBT_FLESH ){
#line 241 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
en_fDensity  = 5000.0f;
#line 242 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
en_fBounceDampNormal  = 0.25f;
#line 243 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
en_fBounceDampParallel  = 0.75f;
#line 244 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}else if(TRUE ){
#line 245 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
en_fDensity  = 5000.0f;
#line 246 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 249 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_dptParticles  = eSpawn  . dptParticles ;
#line 250 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if(m_dptParticles  == DPT_AFTERBURNER )
#line 251 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{
#line 252 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
Particles_AfterBurner_Prepare  (this );
#line 253 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 254 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_betStain  = eSpawn  . betStain ;
#line 255 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_iBodyType  = (INDEX) eSpawn  . Eeibt ;
#line 256 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
GetModelObject  () -> SetData  (eSpawn  . pmd );
#line 257 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
GetModelObject  () -> mo_toTexture  . SetData  (eSpawn  . ptd );
#line 258 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
GetModelObject  () -> mo_toReflection  . SetData  (eSpawn  . ptdRefl );
#line 259 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
GetModelObject  () -> mo_toSpecular  . SetData  (eSpawn  . ptdSpec );
#line 260 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
GetModelObject  () -> mo_toBump  . SetData  (eSpawn  . ptdBump );
#line 261 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
GetModelObject  () -> PlayAnim  (eSpawn  . iModelAnim  , AOF_LOOPING );
#line 262 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
GetModelObject  () -> mo_Stretch  = FLOAT3D (eSpawn  . fSize  , eSpawn  . fSize  , eSpawn  . fSize );
#line 263 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
GetModelObject  () -> mo_Stretch  (1) *= eSpawn  . vStretch  (1);
#line 264 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
GetModelObject  () -> mo_Stretch  (2) *= eSpawn  . vStretch  (2);
#line 265 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
GetModelObject  () -> mo_Stretch  (3) *= eSpawn  . vStretch  (3);
#line 268 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
GetModelObject  () -> mo_colBlendColor  = eSpawn  . colDebris  | CT_OPAQUE ;
#line 269 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_bCustomShading  = eSpawn  . bCustomShading ;
#line 270 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if(m_bCustomShading )
#line 271 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{
#line 272 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
en_ulFlags  |= ENF_NOSHADINGINFO ;
#line 273 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 274 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_aShadingDirection  = eSpawn  . aShadingDirection ;
#line 275 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_colCustomAmbient  = eSpawn  . colCustomAmbient ;
#line 276 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_colCustomDiffuse  = eSpawn  . colCustomDiffuse ;
#line 277 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_bImmaterialASAP  = eSpawn  . bImmaterialASAP ;
#line 278 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_fDustStretch  = eSpawn  . fDustStretch ;
#line 279 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_penFallFXPapa  = eSpawn  . penFallFXPapa ;
#line 281 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
ModelChangeNotify  ();
#line 282 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
FLOATaabbox3D box ;
#line 283 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
GetBoundingBox  (box );
#line 284 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
FLOAT fEntitySize  = box  . Size  () . MaxNorm  ();
#line 285 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if(fEntitySize  > 0.5f){
#line 286 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
SetCollisionFlags  (ECF_MODEL );
#line 287 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 288 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
en_fCollisionSpeedLimit  += ClampDn  (0.0f , fEntitySize  * 10.0f);
#line 289 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_bFade  = FALSE ;
#line 290 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_fLastStainHitPoint  = FLOAT3D (32000.0f , 32000.0f , 32000.0f);
#line 291 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_ctLeftStains  = 0;
#line 292 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_tmStarted  = _pTimer  -> CurrentTick  ();
#line 293 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_bTouchedGround  = FALSE ;
#line 296 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
FLOAT fWaitBeforeFade  = FRnd  () * 2.0f + 3.0f;
#line 297 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
SetTimerAfter(fWaitBeforeFade );
Jump(STATE_CURRENT, 0x025a0001, FALSE, EBegin());return TRUE;}BOOL CDebris::H0x025a0001_Main_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x025a0001
switch(__eeInput.ee_slEvent)
#line 298 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETouch):{const ETouch&etouch= (ETouch&)__eeInput;

#line 303 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if(etouch  . penOther  -> GetRenderType  () == RT_BRUSH )
#line 304 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{
#line 306 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if(m_penFallFXPapa  != NULL  && ! m_bTouchedGround )
#line 307 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{
#line 309 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
FOREACHINLIST  (CEntity  , en_lnInParent  , m_penFallFXPapa  -> en_lhChildren  , iten )
#line 310 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{
#line 312 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
CEntity  * penNew  = GetWorld  () -> CopyEntityInWorld  (* iten  , GetPlacement  ());
#line 313 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
penNew  -> SetParent  (NULL );
#line 314 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if(IsOfClass  (& * penNew  , & CSoundHolder_DLLClass ))
#line 315 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{
#line 316 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
penNew  -> SendEvent  (EStart  ());
#line 317 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 318 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
else 
#line 319 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{
#line 320 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
penNew  -> SendEvent  (ETrigger  ());
#line 321 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 322 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 323 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 325 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if(m_fDustStretch  > 0 && ! m_bTouchedGround )
#line 326 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{
#line 328 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
CPlacement3D plDust  = GetPlacement  ();
#line 329 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
plDust  . pl_PositionVector  = plDust  . pl_PositionVector  + FLOAT3D (0 , m_fDustStretch  * 0.25f , 0);
#line 331 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
ESpawnEffect  ese ;
#line 332 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
ese  . colMuliplier  = C_WHITE  | CT_OPAQUE ;
#line 333 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
ese  . vStretch  = FLOAT3D (m_fDustStretch  , m_fDustStretch  , m_fDustStretch );
#line 334 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
ese  . vNormal  = FLOAT3D (0 , 1 , 0);
#line 335 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
ese  . betType  = BET_DUST_FALL ;
#line 336 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
CEntityPointer penFX  = CreateEntity  (plDust  , CLASS_BASIC_EFFECT  , WLD_AUTO_ENTITY_ID  , FALSE );
#line 337 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
penFX  -> Initialize  (ese  , FALSE );
#line 338 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 339 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_bTouchedGround  = TRUE ;
#line 342 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
LeaveStain  ();
#line 344 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if(m_iBodyType  == EIBT_ROBOT )
#line 345 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{
#line 347 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
Explode  ();
#line 348 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
SendEvent  (EDeath  ());
#line 349 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
return TRUE;
#line 350 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 351 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 352 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if(m_bImmaterialASAP )
#line 353 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{
#line 354 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
SetCollisionFlags  (ECF_DEBRIS );
#line 355 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 356 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
return TRUE;
#line 357 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}ASSERT(FALSE);break;case(EVENTCODE_EDeath):{const EDeath&e= (EDeath&)__eeInput;
Destroy  (FALSE );Return(STATE_CURRENT,EVoid());return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x025a0002, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default: return FALSE; break;
#line 360 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}return TRUE;}BOOL CDebris::H0x025a0002_Main_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x025a0002

#line 363 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if(m_bDebrisCollision )
#line 364 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{
#line 365 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
SetCollisionFlags  (ECF_MODEL );
#line 366 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 367 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
else 
#line 368 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{
#line 369 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
SetCollisionFlags  (ECF_DEBRIS );
#line 370 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 371 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_fFadeStartTime  = _pTimer  -> CurrentTick  ();
#line 372 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_fFadeTime  = 5.0f;
#line 373 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
m_bFade  = m_bDebrisFade ;
#line 374 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
SetTimerAfter(m_fFadeTime );
Jump(STATE_CURRENT, 0x025a0003, FALSE, EBegin());return TRUE;}BOOL CDebris::H0x025a0003_Main_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x025a0003
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x025a0004, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CDebris::H0x025a0004_Main_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x025a0004
;
#line 376 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
if(m_bDebrisFade )
#line 377 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
{
#line 379 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
Destroy  (FALSE );
#line 380 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
}
#line 381 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
Return(STATE_CURRENT,EVoid());
#line 381 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Debris.es"
return TRUE; ASSERT(FALSE); return TRUE;};