/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"

#include "StdH.h"
#include "EntitiesMP/Effector.h"
#include "EntitiesMP/BackgroundViewer.h"
#include "EntitiesMP/WorldSettingsController.h"

#include <EffectMarker.h>
#include <EffectMarker_tables.h>
CEntityEvent *ENetTrigger::MakeCopy(void) { 	CEntityEvent *peeCopy = new ENetTrigger(*this); 	return peeCopy;}
SLONG ENetTrigger::GetSizeOf(void) { 	return sizeof(*this);}
ENetTrigger::ENetTrigger() : CEntityEvent(EVENTCODE_ENetTrigger) {
}
BOOL ENetTrigger::CheckIDs(void) {	return TRUE ; }

#line 32 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"

extern void CBasicEffect_OnPrecache(CDLLEntityClass *pdec, INDEX iUser);

void CEffectMarker::SetDefaultProperties(void) {
	m_emtType = EMT_NONE ;
	m_penModel = NULL;
	m_tmEffectLife = 10.0f;
	m_penModel2 = NULL;
	m_penEffector = NULL;
	m_fShakeFalloff = 250.0f;
	m_fShakeFade = 3.0f;
	m_fShakeIntensityY = 0.1f;
	m_fShakeFrequencyY = 5.0f;
	m_fShakeIntensityB = 2.5f;
	m_fShakeFrequencyB = 7.2f;
	m_fShakeIntensityZ = 0.0f;
	m_fShakeFrequencyZ = 5.0f;
	m_betType = BET_ROCKET ;
	m_fStretch = 1.0f;
	m_colColor = COLOR(C_WHITE  | CT_TRANSPARENT );
	CMarker::SetDefaultProperties();
}

#line 70 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
void CEffectMarker::Precache(void) 
#line 71 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 72 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
switch(m_betType )
#line 73 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 74 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_BASIC_EFFECT : 
#line 75 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CDLLEntityClass  * pdec  = & CBasicEffect_DLLClass ;
#line 77 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CBasicEffect_OnPrecache  (pdec  , m_emtType );
#line 78 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 79 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 80 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}

#line 83 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
BOOL CEffectMarker::IsTargetValid(SLONG slPropertyOffset,CEntity * penTarget) 
#line 84 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 85 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(penTarget  == NULL )
#line 86 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 87 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
return FALSE ;
#line 88 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 90 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(slPropertyOffset  == offsetof  (CEffectMarker  , m_penModel ) 
#line 91 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
|| slPropertyOffset  == offsetof  (CEffectMarker  , m_penModel2 )){
#line 92 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
return (IsOfClass  (penTarget  , & CModelHolder2_DLLClass ) 
#line 93 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
|| IsOfClass  (penTarget  , & CModelHolder3_DLLClass ));
#line 94 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 95 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
return TRUE ;
#line 96 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}

#line 99 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
BOOL CEffectMarker::HandleEvent(const CEntityEvent & ee) 
#line 100 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 101 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(ee  . ee_slEvent  == EVENTCODE_ETrigger )
#line 102 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 103 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
switch(m_emtType )
#line 104 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 105 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_SET_PLACEMENT : 
#line 106 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 107 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(m_penModel  != NULL  && m_penModel2  != NULL )
#line 108 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 109 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penModel  -> Teleport  (m_penModel2  -> GetPlacement  () , FALSE );
#line 110 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 111 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 112 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 113 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_SET_PARENT : 
#line 114 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 115 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(m_penModel  != NULL  && m_penModel2  != NULL )
#line 116 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 117 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penModel  -> SetParent  (m_penModel2 );
#line 118 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 119 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 120 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 121 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_CLEAR_PARENT : 
#line 122 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 123 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(m_penModel  != NULL )
#line 124 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 125 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penModel  -> SetParent  (NULL );
#line 126 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 127 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 128 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 129 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_SHAKE_IT_BABY : 
#line 130 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 131 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(_pNetwork  -> IsServer  ()){
#line 132 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
SendEvent  (ENetTrigger  () , TRUE );
#line 133 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 135 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CWorldSettingsController  * pwsc  = NULL ;
#line 137 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CBackgroundViewer  * penBcgViewer  = (CBackgroundViewer  *) GetWorld  () -> GetBackgroundViewer  ();
#line 138 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(penBcgViewer  != NULL  && penBcgViewer  -> m_penWorldSettingsController  != NULL )
#line 139 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 140 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  = (CWorldSettingsController  *) & * penBcgViewer  -> m_penWorldSettingsController ;
#line 141 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_tmShakeStarted  = _pTimer  -> CurrentTick  ();
#line 142 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_vShakePos  = GetPlacement  () . pl_PositionVector ;
#line 143 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_fShakeFalloff  = m_fShakeFalloff ;
#line 144 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_fShakeFade  = m_fShakeFade ;
#line 145 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_fShakeIntensityZ  = m_fShakeIntensityZ ;
#line 146 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_tmShakeFrequencyZ  = m_fShakeFrequencyZ ;
#line 147 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_fShakeIntensityY  = m_fShakeIntensityY ;
#line 148 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_tmShakeFrequencyY  = m_fShakeFrequencyY ;
#line 149 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_fShakeIntensityB  = m_fShakeIntensityB ;
#line 150 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_tmShakeFrequencyB  = m_fShakeFrequencyB ;
#line 151 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_bShakeFadeIn  = FALSE ;
#line 152 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 153 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 154 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 155 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_HIDE_ENTITY : 
#line 156 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 157 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(_pNetwork  -> IsServer  ()){
#line 158 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
SendEvent  (ENetTrigger  () , TRUE );
#line 159 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 160 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(m_penTarget  != NULL )
#line 161 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 162 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penTarget  -> SetFlags  (m_penTarget  -> GetFlags  () | ENF_HIDDEN );
#line 163 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 164 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 165 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 166 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_SHOW_ENTITY : 
#line 167 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 168 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(_pNetwork  -> IsServer  ()){
#line 169 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
SendEvent  (ENetTrigger  () , TRUE );
#line 170 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 171 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(m_penTarget  != NULL )
#line 172 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 173 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penTarget  -> SetFlags  (m_penTarget  -> GetFlags  () & ~ ENF_HIDDEN );
#line 174 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 175 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 176 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 177 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_PLAYER_APPEAR : 
#line 178 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(m_penModel  != NULL  && IsOfClass  (m_penModel  , & CModelHolder2_DLLClass )){
#line 180 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CModelObject * pmo  = m_penModel  -> GetModelObject  ();
#line 181 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(pmo  != NULL ){
#line 183 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CPlacement3D plFX  = m_penModel  -> GetPlacement  ();
#line 184 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CEntity  * penFX  = CreateEntity  (plFX  , CLASS_EFFECTOR );
#line 185 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
ESpawnEffector  eSpawnFX ;
#line 186 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . tmLifeTime  = m_tmEffectLife ;
#line 187 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . eetType  = ET_PORTAL_LIGHTNING ;
#line 188 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . eidModel  = m_penModel ;
#line 189 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
penFX  -> Initialize  (eSpawnFX );
#line 190 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 191 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 192 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 193 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_APPEARING_BIG_BLUE_FLARE : 
#line 194 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 196 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CPlacement3D plFX  = GetPlacement  ();
#line 197 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CEntity  * penFX  = CreateEntity  (plFX  , CLASS_EFFECTOR );
#line 198 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
ESpawnEffector  eSpawnFX ;
#line 199 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . tmLifeTime  = m_tmEffectLife ;
#line 200 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . fSize  = 1.0f;
#line 201 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . eetType  = ET_SIZING_BIG_BLUE_FLARE ;
#line 202 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
penFX  -> Initialize  (eSpawnFX );
#line 203 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 204 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 205 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_BLEND_MODELS : 
#line 206 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if((m_penModel  != NULL  && IsOfClass  (m_penModel  , & CModelHolder2_DLLClass ) && 
#line 207 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penModel2  != NULL  && IsOfClass  (m_penModel2  , & CModelHolder2_DLLClass )) || 
#line 208 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
(m_penModel  != NULL  && IsOfClass  (m_penModel  , & CModelHolder3_DLLClass ) && 
#line 209 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penModel2  != NULL  && IsOfClass  (m_penModel2  , & CModelHolder3_DLLClass ))){
#line 210 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(m_penEffector  == NULL ){
#line 211 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CModelObject * pmo1  = m_penModel  -> GetModelObject  ();
#line 212 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CModelObject * pmo2  = m_penModel2  -> GetModelObject  ();
#line 213 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(pmo1  != NULL  && pmo2  != NULL ){
#line 215 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CPlacement3D plFX  = m_penModel  -> GetPlacement  ();
#line 216 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CEntity  * penFX  = CreateEntity  (plFX  , CLASS_EFFECTOR );
#line 217 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
ESpawnEffector  eSpawnFX ;
#line 218 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . tmLifeTime  = m_tmEffectLife ;
#line 219 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . eetType  = ET_MORPH_MODELS ;
#line 220 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . eidModel  = m_penModel ;
#line 221 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . eidModel2  = m_penModel2 ;
#line 222 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
penFX  -> Initialize  (eSpawnFX );
#line 223 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penEffector  = penFX ;
#line 224 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 225 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 226 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
else 
#line 227 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 228 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(_pNetwork  -> IsServer  ()){
#line 229 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
SendEvent  (ENetTrigger  () , TRUE );
#line 230 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 231 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penEffector  -> SendEvent  (ETrigger  ());
#line 232 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 233 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 234 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 235 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_DISAPPEAR_MODEL : 
#line 236 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(m_penModel  != NULL  && IsOfClass  (m_penModel  , & CModelHolder2_DLLClass )){
#line 237 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(m_penEffector  == NULL ){
#line 238 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CModelObject * pmo  = m_penModel  -> GetModelObject  ();
#line 239 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(pmo  != NULL ){
#line 241 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CPlacement3D plFX  = m_penModel  -> GetPlacement  ();
#line 242 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CEntity  * penFX  = CreateEntity  (plFX  , CLASS_EFFECTOR );
#line 243 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
ESpawnEffector  eSpawnFX ;
#line 244 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . tmLifeTime  = m_tmEffectLife ;
#line 245 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . eetType  = ET_DISAPPEAR_MODEL ;
#line 246 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . eidModel  = m_penModel ;
#line 247 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
penFX  -> Initialize  (eSpawnFX );
#line 248 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penEffector  = penFX ;
#line 249 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 250 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}else {
#line 251 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penEffector  -> SendEvent  (ETrigger  ());
#line 252 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 253 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 254 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 255 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_APPEAR_MODEL : 
#line 256 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(m_penModel  != NULL  && IsOfClass  (m_penModel  , & CModelHolder2_DLLClass )){
#line 257 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(m_penEffector  == NULL ){
#line 258 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CModelObject * pmo  = m_penModel  -> GetModelObject  ();
#line 259 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(pmo  != NULL ){
#line 261 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CPlacement3D plFX  = m_penModel  -> GetPlacement  ();
#line 262 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CEntity  * penFX  = CreateEntity  (plFX  , CLASS_EFFECTOR );
#line 263 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
ESpawnEffector  eSpawnFX ;
#line 264 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . tmLifeTime  = m_tmEffectLife ;
#line 265 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . eetType  = ET_APPEAR_MODEL ;
#line 266 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . eidModel  = m_penModel ;
#line 267 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
penFX  -> Initialize  (eSpawnFX );
#line 268 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penEffector  = penFX ;
#line 269 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 270 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}else {
#line 271 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penEffector  -> SendEvent  (ETrigger  ());
#line 272 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 273 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 274 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 275 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_BASIC_EFFECT : 
#line 276 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 278 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CPlacement3D plEffect  = GetPlacement  ();
#line 279 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CEntityPointer penEffect  = CreateEntity  (plEffect  , CLASS_BASIC_EFFECT );
#line 280 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
ESpawnEffect  eSpawnEffect ;
#line 281 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnEffect  . colMuliplier  = C_WHITE  | CT_OPAQUE ;
#line 282 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnEffect  . betType  = m_betType ;
#line 283 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnEffect  . vStretch  = FLOAT3D (m_fStretch  , m_fStretch  , m_fStretch );
#line 284 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
penEffect  -> Initialize  (eSpawnEffect );
#line 285 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 286 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 287 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_GLARE : 
#line 288 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CWorldSettingsController  * pwsc  = GetWSC  (this );
#line 289 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(pwsc  != NULL )
#line 290 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 291 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_colGlade  = m_colColor ;
#line 292 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_tmGlaringStarted  = _pTimer  -> CurrentTick  ();
#line 293 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_tmGlaringEnded  = pwsc  -> m_tmGlaringStarted  + m_tmEffectLife  , 
#line 294 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_fGlaringFadeInRatio  = 0.2f;
#line 295 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_fGlaringFadeOutRatio  = 0.7f;
#line 296 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 297 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 298 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 299 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 300 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
else if(ee  . ee_slEvent  == EVENTCODE_ENetTrigger )
#line 301 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 302 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(_pNetwork  -> IsServer  ()){
#line 303 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
return TRUE ;
#line 304 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 306 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
switch(m_emtType )
#line 307 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 308 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_SHAKE_IT_BABY : 
#line 309 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 311 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CWorldSettingsController  * pwsc  = NULL ;
#line 313 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CBackgroundViewer  * penBcgViewer  = (CBackgroundViewer  *) GetWorld  () -> GetBackgroundViewer  ();
#line 314 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(penBcgViewer  != NULL  && penBcgViewer  -> m_penWorldSettingsController  != NULL )
#line 315 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 316 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  = (CWorldSettingsController  *) & * penBcgViewer  -> m_penWorldSettingsController ;
#line 317 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_tmShakeStarted  = _pTimer  -> CurrentTick  ();
#line 318 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_vShakePos  = GetPlacement  () . pl_PositionVector ;
#line 319 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_fShakeFalloff  = m_fShakeFalloff ;
#line 320 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_fShakeFade  = m_fShakeFade ;
#line 321 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_fShakeIntensityZ  = m_fShakeIntensityZ ;
#line 322 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_tmShakeFrequencyZ  = m_fShakeFrequencyZ ;
#line 323 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_fShakeIntensityY  = m_fShakeIntensityY ;
#line 324 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_tmShakeFrequencyY  = m_fShakeFrequencyY ;
#line 325 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_fShakeIntensityB  = m_fShakeIntensityB ;
#line 326 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_tmShakeFrequencyB  = m_fShakeFrequencyB ;
#line 327 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_bShakeFadeIn  = FALSE ;
#line 328 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 329 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 330 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 331 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_HIDE_ENTITY : 
#line 332 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 333 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(m_penTarget  != NULL )
#line 334 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 335 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penTarget  -> SetFlags  (m_penTarget  -> GetFlags  () | ENF_HIDDEN );
#line 336 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 337 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 338 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 339 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_SHOW_ENTITY : 
#line 340 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 341 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(m_penTarget  != NULL )
#line 342 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 343 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penTarget  -> SetFlags  (m_penTarget  -> GetFlags  () & ~ ENF_HIDDEN );
#line 344 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 345 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 346 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 347 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_BLEND_MODELS : 
#line 348 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 349 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if((m_penModel  != NULL  && IsOfClass  (m_penModel  , & CModelHolder2_DLLClass ) && 
#line 350 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penModel2  != NULL  && IsOfClass  (m_penModel2  , & CModelHolder2_DLLClass )) || 
#line 351 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
(m_penModel  != NULL  && IsOfClass  (m_penModel  , & CModelHolder3_DLLClass ) && 
#line 352 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penModel2  != NULL  && IsOfClass  (m_penModel2  , & CModelHolder3_DLLClass ))){
#line 353 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(m_penEffector  != NULL ){
#line 354 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penEffector  -> SendEvent  (ETrigger  ());
#line 355 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 356 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 357 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 358 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 359 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_DISAPPEAR_MODEL : 
#line 360 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 361 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(m_penModel  != NULL  && IsOfClass  (m_penModel  , & CModelHolder2_DLLClass )){
#line 362 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(m_penEffector  != NULL ){
#line 363 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penEffector  -> SendEvent  (ETrigger  ());
#line 364 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 365 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 366 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 367 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 368 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_APPEAR_MODEL : 
#line 369 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 370 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(m_penModel  != NULL  && IsOfClass  (m_penModel  , & CModelHolder2_DLLClass )){
#line 371 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(m_penEffector  != NULL ){
#line 372 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penEffector  -> SendEvent  (ETrigger  ());
#line 373 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 374 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 375 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 376 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 377 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_GLARE : 
#line 378 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CWorldSettingsController  * pwsc  = GetWSC  (this );
#line 379 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(pwsc  != NULL )
#line 380 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 381 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_colGlade  = m_colColor ;
#line 382 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_tmGlaringStarted  = _pTimer  -> CurrentTick  ();
#line 383 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_tmGlaringEnded  = pwsc  -> m_tmGlaringStarted  + m_tmEffectLife  , 
#line 384 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_fGlaringFadeInRatio  = 0.2f;
#line 385 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
pwsc  -> m_fGlaringFadeOutRatio  = 0.7f;
#line 386 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 387 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 388 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 389 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
return TRUE ;
#line 390 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 391 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
else if(ee  . ee_slEvent  == EVENTCODE_EActivate )
#line 392 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 393 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
switch(m_emtType )
#line 394 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 395 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_APPEAR_DISAPPEAR : 
#line 396 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(m_penModel  != NULL  && IsOfClass  (m_penModel  , & CModelHolder2_DLLClass )){
#line 398 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CModelObject * pmo  = m_penModel  -> GetModelObject  ();
#line 399 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(pmo  != NULL ){
#line 401 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CPlacement3D plFX  = m_penModel  -> GetPlacement  ();
#line 402 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CEntity  * penFX  = CreateEntity  (plFX  , CLASS_EFFECTOR );
#line 403 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
ESpawnEffector  eSpawnFX ;
#line 404 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . tmLifeTime  = m_tmEffectLife ;
#line 405 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . eetType  = ET_APPEAR_MODEL_NOW ;
#line 406 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . eidModel  = m_penModel ;
#line 407 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
penFX  -> Initialize  (eSpawnFX );
#line 408 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penEffector  = penFX ;
#line 409 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 410 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 411 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 412 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 413 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 414 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
else if(ee  . ee_slEvent  == EVENTCODE_EDeactivate )
#line 415 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 416 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
switch(m_emtType )
#line 417 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
{
#line 418 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
case EMT_APPEAR_DISAPPEAR : 
#line 419 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(m_penModel  != NULL  && IsOfClass  (m_penModel  , & CModelHolder2_DLLClass )){
#line 421 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CModelObject * pmo  = m_penModel  -> GetModelObject  ();
#line 422 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
if(pmo  != NULL ){
#line 424 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CPlacement3D plFX  = m_penModel  -> GetPlacement  ();
#line 425 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
CEntity  * penFX  = CreateEntity  (plFX  , CLASS_EFFECTOR );
#line 426 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
ESpawnEffector  eSpawnFX ;
#line 427 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . tmLifeTime  = m_tmEffectLife ;
#line 428 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . eetType  = ET_DISAPPEAR_MODEL_NOW ;
#line 429 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
eSpawnFX  . eidModel  = m_penModel ;
#line 430 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
penFX  -> Initialize  (eSpawnFX );
#line 431 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penEffector  = penFX ;
#line 432 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 433 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 434 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
break ;
#line 435 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 436 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
#line 437 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
return FALSE ;
#line 438 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
}
BOOL CEffectMarker::
#line 442 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CEffectMarker_Main
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CEffectMarker::Main expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 445 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
InitAsEditorModel  ();
#line 446 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 447 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 449 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
SetFlagOn  (ENF_MARKDESTROY );
#line 450 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
SetFlagOn  (ENF_NONETCONNECT );
#line 451 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
SetFlagOff  (ENF_PROPSCHANGED );
#line 454 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
SetModel  (MODEL_MARKER );
#line 455 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
SetModelMainTexture  (TEXTURE_MARKER );
#line 457 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
m_penEffector  = NULL ;
#line 458 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
Return(STATE_CURRENT,EVoid());
#line 458 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/EffectMarker.es"
return TRUE; ASSERT(FALSE); return TRUE;};