/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 2 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"

#include "StdH.h"
#include "Models/Items/ItemHolder/ItemHolder.h"
#include "EntitiesMP/Player.h"

#include <Item.h>
#include <Item_tables.h>
CEntityEvent *EReceiveItem::MakeCopy(void) { 	CEntityEvent *peeCopy = new EReceiveItem(*this); 	return peeCopy;}
SLONG EReceiveItem::GetSizeOf(void) { 	return sizeof(*this);}
EReceiveItem::EReceiveItem() : CEntityEvent(EVENTCODE_EReceiveItem) {
}
BOOL EReceiveItem::CheckIDs(void) {	return TRUE ; }

CEntityEvent *EMarkPicked::MakeCopy(void) { 	CEntityEvent *peeCopy = new EMarkPicked(*this); 	return peeCopy;}
SLONG EMarkPicked::GetSizeOf(void) { 	return sizeof(*this);}
EMarkPicked::EMarkPicked() : CEntityEvent(EVENTCODE_EMarkPicked) {
	ClearToDefault(eidPlayer);
}
BOOL EMarkPicked::CheckIDs(void) {	return TRUE && eidPlayer.IsValid(); }

CEntityEvent *ESetType::MakeCopy(void) { 	CEntityEvent *peeCopy = new ESetType(*this); 	return peeCopy;}
SLONG ESetType::GetSizeOf(void) { 	return sizeof(*this);}
ESetType::ESetType() : CEntityEvent(EVENTCODE_ESetType) {
	ClearToDefault(iType);
}
BOOL ESetType::CheckIDs(void) {	return TRUE ; }

#line 19 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"

// used to render certain entities only for certain players (like picked items, etc.)
extern ULONG _ulPlayerRenderingMask;

void CItem::SetDefaultProperties(void) {
	m_strName = "Item";
	m_strDescription = "";
	m_fValue = 0.0f;
	m_fRespawnTime = 0.0f;
	m_fCustomRespawnTime = 0.0f;
	m_bRespawn = FALSE ;
	m_penTarget = NULL;
	m_bPickupOnce = FALSE ;
	m_soPick.SetOwner(this);
	m_soPick.Stop(FALSE);
	m_fPickSoundLen = 0.0f;
	m_bDropped = FALSE ;
	m_ulPickedMask = 0;
	m_bFloating = FALSE ;
	m_ulRecentlyPickedMask = 0;
	CMovableModelEntity::SetDefaultProperties();
}
void CItem::AdjustDifficulty(void) 
#line 54 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
{
#line 55 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
void CItem::SetItemType(INDEX iType) 
#line 58 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
{
#line 59 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}

#line 62 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
void CItem::AdjustMipFactor(FLOAT & fMipFactor) 
#line 63 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
{
#line 64 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
if(en_RenderType  == CEntity  :: RT_MODEL )
#line 65 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
{
#line 67 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
CAttachmentModelObject  * pamo  = GetModelObject  () -> GetAttachmentModel  (ITEMHOLDER_ATTACHMENT_FLARE );
#line 68 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
if(pamo  != NULL )
#line 69 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
{
#line 70 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
FLOAT fRatio  = (Clamp  (fMipFactor  , 5.0f , 7.0f) - 5.0f) / 2.0f;
#line 71 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
UBYTE  ubRatio  = UBYTE  (255 * fRatio );
#line 72 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
COLOR colMutiply  = RGBToColor  (ubRatio  , ubRatio  , ubRatio ) | CT_OPAQUE ;
#line 73 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
pamo  -> amo_moModelObject  . mo_colBlendColor  = colMutiply ;
#line 74 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
#line 75 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
#line 78 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
if(m_ulPickedMask  == 0){
#line 80 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return ;
#line 81 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
#line 83 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
BOOL bFlare  = TRUE ;
#line 85 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
if(_ulPlayerRenderingMask  & m_ulPickedMask ){
#line 87 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
extern  INDEX plr_bRenderPicked ;
#line 88 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
if(! plr_bRenderPicked ){
#line 90 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
fMipFactor  = UpperLimit  (0.0f);
#line 91 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
#line 93 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
extern  INDEX plr_bRenderPickedParticles ;
#line 94 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
if(! plr_bRenderPickedParticles ){
#line 96 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
bFlare  = FALSE ;
#line 97 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
#line 98 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
#line 101 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}

#line 104 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
BOOL CItem::ShowItemParticles(void) 
#line 105 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
{
#line 107 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
if(_ulPlayerRenderingMask  & m_ulPickedMask ){
#line 109 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
extern  INDEX plr_bRenderPickedParticles ;
#line 110 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
if(! plr_bRenderPickedParticles ){
#line 112 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return FALSE ;
#line 113 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
#line 114 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
#line 116 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return TRUE ;
#line 117 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}

#line 121 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
BOOL CItem::MarkRecentlyPickedBy(CEntity * pen) 
#line 122 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
{
#line 123 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
if(! IsOfClass  (pen  , & CPlayer_DLLClass )){
#line 124 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return FALSE ;
#line 125 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
#line 126 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
INDEX iPlayer  = ((CPlayerEntity  *) pen ) -> GetMyPlayerIndex  ();
#line 127 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
BOOL bPickedAlready  = (1 << iPlayer ) & m_ulRecentlyPickedMask ;
#line 128 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
m_ulRecentlyPickedMask  |= (1 << iPlayer );
#line 129 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return bPickedAlready ;
#line 130 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}

#line 133 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
BOOL CItem::WasRecentlyPickedBy(CEntity * pen) 
#line 134 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
{
#line 135 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
if(! IsOfClass  (pen  , & CPlayer_DLLClass )){
#line 136 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return FALSE ;
#line 137 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
#line 138 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
INDEX iPlayer  = ((CPlayerEntity  *) pen ) -> GetMyPlayerIndex  ();
#line 139 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
BOOL bPickedAlready  = (1 << iPlayer ) & m_ulRecentlyPickedMask ;
#line 140 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return bPickedAlready ;
#line 141 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}

#line 144 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
BOOL CItem::MarkPickedBy(CEntity * pen) 
#line 145 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
{
#line 146 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
if(! IsOfClass  (pen  , & CPlayer_DLLClass )){
#line 147 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return FALSE ;
#line 148 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
#line 149 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
INDEX iPlayer  = ((CPlayerEntity  *) pen ) -> GetMyPlayerIndex  ();
#line 150 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
BOOL bPickedAlready  = (1 << iPlayer ) & m_ulPickedMask ;
#line 151 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
m_ulPickedMask  |= (1 << iPlayer );
#line 152 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return bPickedAlready ;
#line 153 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}

#line 156 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
BOOL CItem::WasPickedBy(CEntity * pen) 
#line 157 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
{
#line 158 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
if(! IsOfClass  (pen  , & CPlayer_DLLClass )){
#line 159 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return FALSE ;
#line 160 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
#line 161 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
INDEX iPlayer  = ((CPlayerEntity  *) pen ) -> GetMyPlayerIndex  ();
#line 162 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
BOOL bPickedAlready  = (1 << iPlayer ) & m_ulPickedMask ;
#line 163 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return bPickedAlready ;
#line 164 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}

#line 167 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
BOOL CItem::AdjustShadingParameters(FLOAT3D & vLightDirection,COLOR & colLight,COLOR & colAmbient) 
#line 168 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
{
#line 171 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
{
#line 173 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
colLight  = 0x40404040;
#line 174 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
colAmbient  = 0x60606060;
#line 175 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
#line 186 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
vLightDirection  = FLOAT3D (- 1 , - 1 , - 1);
#line 187 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
vLightDirection  . Normalize  ();
#line 188 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
vLightDirection  *= GetRotationMatrix  ();
#line 191 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return FALSE ;
#line 192 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}

#line 197 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
void CItem::InitializeItem(void) {
#line 198 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
InitAsModel  ();
#line 199 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
SetFlags  (GetFlags  () | ENF_SEETHROUGH );
#line 201 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
if(m_bFloating ){
#line 202 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
SetPhysicsFlags  (EPF_MODEL_FLYING );
#line 203 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}else {
#line 204 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
SetPhysicsFlags  (EPF_MODEL_SLIDING );
#line 205 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
#line 207 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
SetCollisionFlags  (ECF_ITEM );
#line 208 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
SetFlagOn  (ENF_CLIENTHANDLING );
#line 211 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
en_fDeceleration  = 60.0f;
#line 214 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
SetModel  (MODEL_ITEM );
#line 215 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
SetDesiredTranslation  (FLOAT3D (0 , 0 , 0));
#line 216 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}

#line 224 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
void CItem::AddItem(ULONG ulIDModel,ULONG ulIDTexture,
#line 225 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
ULONG ulIDReflectionTexture,ULONG ulIDSpecularTexture,ULONG ulIDBumpTexture) {
#line 226 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
AddAttachmentToModel  (this  , * GetModelObject  () , ITEMHOLDER_ATTACHMENT_ITEM  , ulIDModel  , ulIDTexture  , 
#line 227 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
ulIDReflectionTexture  , ulIDSpecularTexture  , ulIDBumpTexture );
#line 228 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}

#line 229 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
void CItem::AddItemSpecial(INDEX iAttachmentPos,ULONG ulIDModel,ULONG ulIDTexture,
#line 230 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
ULONG ulIDReflectionTexture,ULONG ulIDSpecularTexture,ULONG ulIDBumpTexture) {
#line 231 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
AddAttachmentToModel  (this  , * GetModelObject  () , iAttachmentPos  , ulIDModel  , ulIDTexture  , 
#line 232 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
ulIDReflectionTexture  , ulIDSpecularTexture  , ulIDBumpTexture );
#line 233 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}

#line 236 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
void CItem::AddItemAttachment(INDEX iAttachment,ULONG ulIDModel,ULONG ulIDTexture,
#line 237 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
ULONG ulIDReflectionTexture,ULONG ulIDSpecularTexture,ULONG ulIDBumpTexture) {
#line 238 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
CModelObject & mo  = GetModelObject  () -> GetAttachmentModel  (ITEMHOLDER_ATTACHMENT_ITEM ) -> amo_moModelObject ;
#line 239 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
AddAttachmentToModel  (this  , mo  , iAttachment  , ulIDModel  , ulIDTexture  , 
#line 240 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
ulIDReflectionTexture  , ulIDSpecularTexture  , ulIDBumpTexture );
#line 241 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}

#line 243 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
void CItem::SetItemAttachmentAnim(INDEX iAttachment,INDEX iAnim) 
#line 244 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
{
#line 245 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
CModelObject & mo  = 
#line 246 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
GetModelObject  () -> GetAttachmentModel  (ITEMHOLDER_ATTACHMENT_ITEM ) -> amo_moModelObject  . 
#line 247 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
GetAttachmentModel  (iAttachment ) -> amo_moModelObject ;
#line 248 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
mo  . PlayAnim  (iAnim  , 0);
#line 249 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}

#line 252 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
void CItem::AddFlare(ULONG ulIDModel,ULONG ulIDTexture,
#line 253 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
const FLOAT3D & vPos,const FLOAT3D & vStretch) 
#line 254 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
{
#line 256 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
if(! m_bRespawn  && ! m_bDropped )
#line 257 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
{
#line 258 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
AddAttachmentToModel  (this  , * GetModelObject  () , 
#line 259 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
ITEMHOLDER_ATTACHMENT_FLARE  , ulIDModel  , ulIDTexture  , 0 , 0 , 0);
#line 260 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
CAttachmentModelObject  & amo  = * GetModelObject  () -> GetAttachmentModel  (ITEMHOLDER_ATTACHMENT_FLARE );
#line 261 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
amo  . amo_moModelObject  . StretchModel  (vStretch );
#line 262 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
amo  . amo_plRelative  . pl_PositionVector  = vPos ;
#line 263 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
#line 264 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}

#line 267 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
void CItem::StretchItem(const FLOAT3D & vStretch) {
#line 268 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
CModelObject & mo  = GetModelObject  () -> GetAttachmentModel  (ITEMHOLDER_ATTACHMENT_ITEM ) -> amo_moModelObject ;
#line 269 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
mo  . StretchModel  (vStretch );
#line 270 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
ModelChangeNotify  ();
#line 271 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}

#line 276 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
SLONG CItem::GetUsedMemory(void) 
#line 277 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
{
#line 279 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
SLONG  slUsedMemory  = sizeof  (CItem ) - sizeof  (CMovableModelEntity ) + CMovableModelEntity  :: GetUsedMemory  ();
#line 281 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
slUsedMemory  += m_strDescription  . Length  ();
#line 282 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
slUsedMemory  += m_strName  . Length  ();
#line 283 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
slUsedMemory  += 1 * sizeof  (CSoundObject);
#line 284 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return slUsedMemory ;
#line 285 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
BOOL CItem::
#line 294 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
ItemCollected(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CItem_ItemCollected
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EPass, "CItem::ItemCollected expects 'EPass' as input!");	const EPass &epass = (const EPass &)__eeInput;Return(STATE_CURRENT,EVoid());return TRUE; ASSERT(FALSE); return TRUE;};BOOL CItem::
#line 300 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
ItemLoop(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CItem_ItemLoop
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CItem::ItemLoop expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 302 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
SetFlagOn  (ENF_CLIENTHANDLING );
#line 303 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
m_fCustomRespawnTime  = ClampDn  (m_fCustomRespawnTime  , 0.0f);
#line 305 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
SetTimerAfter(0.1f);
Jump(STATE_CURRENT, 0x03200005, FALSE, EBegin());return TRUE;}BOOL CItem::H0x03200005_ItemLoop_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x03200005
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ESetType):{const ESetType&eSetType= (ESetType&)__eeInput;

#line 308 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
SetItemType  (eSetType  . iType );
#line 309 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return TRUE;
#line 310 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x03200006, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default: return FALSE; break;
#line 312 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}return TRUE;}BOOL CItem::H0x03200006_ItemLoop_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x03200006
;
#line 314 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
AdjustDifficulty  ();
#line 316 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x03200007, FALSE, EBegin());return TRUE;}BOOL CItem::H0x03200007_ItemLoop_03(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x03200007
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_EPass):{const EPass&epass= (EPass&)__eeInput;

#line 319 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
if(! IsOfClass  (epass  . penOther  , & CPlayer_DLLClass )){
#line 320 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return FALSE;
#line 321 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
#line 322 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
if(! (m_bPickupOnce  || m_bRespawn )){
#line 323 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
SendToTarget  (m_penTarget  , EET_TRIGGER  , epass  . penOther );
#line 324 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
m_penTarget  = NULL ;
#line 325 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
#line 327 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
Call(STATE_CURRENT, STATE_CItem_ItemCollected, TRUE, epass );return TRUE;
#line 328 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return TRUE;
#line 329 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}ASSERT(FALSE);break;case(EVENTCODE_EMarkPicked):{const EMarkPicked&eMark= (EMarkPicked&)__eeInput;

#line 331 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
MarkPickedBy  ((CEntity  *) eMark  . eidPlayer );
#line 332 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return TRUE;
#line 333 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}ASSERT(FALSE);break;case(EVENTCODE_EReceiveItem):{const EReceiveItem&e= (EReceiveItem&)__eeInput;

#line 335 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
if(! _pNetwork  -> IsServer  ()){
#line 336 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
Call(STATE_CURRENT, STATE_CItem_ItemReceived, TRUE, EVoid  ());return TRUE;
#line 337 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
#line 338 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return TRUE;
#line 339 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}ASSERT(FALSE);break;case(EVENTCODE_ESetType):{const ESetType&eSetType= (ESetType&)__eeInput;

#line 341 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
SetItemType  (eSetType  . iType );
#line 342 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return TRUE;
#line 343 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}ASSERT(FALSE);break;case(EVENTCODE_EDeactivate):{const EDeactivate&eDeactivate= (EDeactivate&)__eeInput;

#line 345 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
Call(STATE_CURRENT, STATE_CItem_ItemDeActivate, TRUE, eDeactivate );return TRUE;
#line 346 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return TRUE;
#line 347 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}ASSERT(FALSE);break;case(EVENTCODE_EActivate):{const EActivate&eActivate= (EActivate&)__eeInput;

#line 349 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
Call(STATE_CURRENT, STATE_CItem_ItemActivate, TRUE, eActivate );return TRUE;
#line 350 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return TRUE;
#line 351 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}ASSERT(FALSE);break;case(EVENTCODE_EEnd):{const EEnd&e= (EEnd&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x03200008, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default: return FALSE; break;
#line 353 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}return TRUE;}BOOL CItem::H0x03200008_ItemLoop_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x03200008

#line 355 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
SetTimerAfter(m_fPickSoundLen  + 0.5f);
Jump(STATE_CURRENT, 0x03200009, FALSE, EBegin());return TRUE;}BOOL CItem::H0x03200009_ItemLoop_05(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x03200009
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x0320000a, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CItem::H0x0320000a_ItemLoop_06(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0320000a
;
#line 357 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
if(m_bDropped ){
#line 358 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
Destroy  ();
#line 359 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}else {
#line 360 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
Destroy  (FALSE );
#line 361 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
#line 362 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
Return(STATE_CURRENT,EVoid());
#line 362 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CItem::
#line 366 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
ItemReceived(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CItem_ItemReceived
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CItem::ItemReceived expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 369 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
SwitchToEditorModel  ();
#line 370 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
if((m_bPickupOnce  || m_bRespawn )){
#line 371 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
SendToTarget  (m_penTarget  , EET_TRIGGER  , NULL );
#line 372 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}
#line 375 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
if(!(m_bRespawn )){ Jump(STATE_CURRENT,0x0320000f, FALSE, EInternal());return TRUE;}
#line 376 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
ASSERT  (m_fRespawnTime  > 0.0f);
#line 379 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
SetTimerAfter(m_fRespawnTime );
Jump(STATE_CURRENT, 0x0320000c, FALSE, EBegin());return TRUE;}BOOL CItem::H0x0320000c_ItemReceived_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x0320000c
switch(__eeInput.ee_slEvent){case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_ETimer):{const ETimer&e= (ETimer&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x0320000d, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default:{return TRUE;}ASSERT(FALSE);break;
#line 383 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}return TRUE;}BOOL CItem::H0x0320000d_ItemReceived_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0320000d

#line 385 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
SwitchToModel  ();
#line 386 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
m_ulRecentlyPickedMask  = 0;Jump(STATE_CURRENT,0x0320000e, FALSE, EInternal());return TRUE;}BOOL CItem::H0x0320000f_ItemReceived_04(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0320000f
{
#line 389 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
Return(STATE_CURRENT,EEnd  ());
#line 389 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return TRUE;
#line 390 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
}Jump(STATE_CURRENT,0x0320000e, FALSE, EInternal());return TRUE;}
BOOL CItem::H0x0320000e_ItemReceived_03(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x0320000e

#line 391 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
Return(STATE_CURRENT,EVoid());
#line 391 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CItem::
#line 397 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
ItemActivate(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CItem_ItemActivate
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EActivate, "CItem::ItemActivate expects 'EActivate' as input!");	const EActivate &eAct = (const EActivate &)__eeInput;Return(STATE_CURRENT,EVoid());return TRUE; ASSERT(FALSE); return TRUE;};BOOL CItem::
#line 398 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Item.es"
ItemDeActivate(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CItem_ItemDeActivate
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EDeactivate, "CItem::ItemDeActivate expects 'EDeactivate' as input!");	const EDeactivate &eDeAct = (const EDeactivate &)__eeInput;Return(STATE_CURRENT,EVoid());return TRUE; ASSERT(FALSE); return TRUE;};