/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _Marker_INCLUDED
#define _Marker_INCLUDED 1
extern "C" DECL_DLL CDLLEntityClass CMarker_DLLClass;
class CMarker : public CEntity {
public:
virtual const CTString &GetName(void) const { return m_strName; };
virtual CEntity *GetTarget(void) const { return m_penTarget; };
virtual BOOL IsTargetable(void) const { return TRUE; };
	DECL_DLL virtual void SetDefaultProperties(void);
	CTString m_strName;
	CTString m_strDescription;
	CEntityPointer m_penTarget;
   
#line 26 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Marker.es"
const CTString & GetDescription(void)const;
   
#line 36 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Marker.es"
BOOL MovesByTargetedRoute(CTString & strTargetProperty)const;
   
#line 41 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Marker.es"
BOOL DropsMarker(CTFileName & fnmMarkerClass,CTString & strTargetProperty)const;
  
#line 49 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Marker.es"
virtual BOOL IsMarker(void)const;
   
#line 56 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Marker.es"
SLONG GetUsedMemory(void);
#define  STATE_CMarker_Main 1
	BOOL 
#line 70 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Marker.es"
Main(const CEntityEvent &__eeInput);
};
#endif // _Marker_INCLUDED
