/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 3 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"

#include "stdH.h"
#include <Engine/Base/Timer.h>
#include <Engine/Terrain/Terrain.h>
#include <math.h>
#include <Engine/Graphics/Color.h>

#include <SunMoon.h>
#include <SunMoon_tables.h>
#line 20 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"

extern COLOR g_colNewGameShadeColor;

#define C_WHITE_OPAQUE	(C_WHITE|CT_OPAQUE)

	inline COLOR AverageColor(COLOR col1, COLOR col2)
	{
		UBYTE uR1, uG1, uB1;
		UBYTE uR2, uG2, uB2;
		ColorToRGB(col1, uR1, uG1, uB1);
		ColorToRGB(col2, uR2, uG2, uB2);
		uR1 = (uR1>>1) + (uR2>>1);
		uG1 = (uG1>>1) + (uG2>>1);
		uB1 = (uB1>>1) + (uB2>>1);
		return RGBToColor(uR1, uG1, uB1);
	}

void CSunMoon::SetDefaultProperties(void) {
	m_strName = "SunMoon ";
	m_epLight = NULL;
	m_epSky = NULL;
	m_epSkyHorizon = NULL;
	m_epHaze = NULL;
	m_epFog = NULL;
	m_fLength = 10;
	m_fHeight = 5;
	m_bWeatherSun = TRUE ;
	m_colRainAmbient = C_WHITE_OPAQUE ;
	m_colHazeDefault = C_WHITE_OPAQUE ;
	m_colFogDefault = C_WHITE_OPAQUE ;
	m_bActive = TRUE ;
	m_lftSun = LFT_NONE ;
	m_lftMoon = LFT_NONE ;
	m_fnmColAniFile = CTString("");
	m_iSkyColAni = 0;
	m_aoSkyColAni.SetData(NULL);

	m_epSunModel = NULL;
	m_epMoonModel = NULL;
	m_eetMorningEvent = EET_START ;
	m_eetEveningEvent = EET_STOP ;
	m_epMorningTarget = NULL;
	m_epEveningTarget = NULL;
	m_bNoon = TRUE ;
	m_bNight = TRUE ;
	CMovableModelEntity::SetDefaultProperties();
}

#line 81 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
void CSunMoon::InitModelHolder(void) 
#line 82 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 83 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
InitAsEditorModel  ();
#line 85 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
BOOL bLoadOK  = TRUE ;
#line 87 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
SetModel  (MODEL_SUNMOON );
#line 89 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
GetModelObject  () -> StretchModel  (FLOAT3D (m_fLength  , m_fHeight  , m_fLength ));
#line 91 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
SetPhysicsFlags  (EPF_MODEL_IMMATERIAL );
#line 92 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
SetCollisionFlags  (ECF_IMMATERIAL );
#line 94 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
SetFlags  (GetFlags  () & ~ ENF_CLUSTERSHADOWS );
#line 96 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
return ;
#line 97 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}

#line 99 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
BOOL CSunMoon::IsTargetValid(SLONG slPropertyOffset,CEntity * penTarget) 
#line 100 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 101 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(penTarget  == NULL ){return FALSE ;}
#line 103 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
ULONG  ulFirst ;
#line 106 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
ulFirst  = offsetof  (CSunMoon  , m_epLight );
#line 107 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(slPropertyOffset  == ulFirst ){return IsDerivedFromClass  (penTarget  , & CLight_DLLClass );}
#line 109 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
ulFirst  = offsetof  (CSunMoon  , m_epSky );
#line 110 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(slPropertyOffset  == ulFirst ){return IsDerivedFromClass  (penTarget  , & CModelHolder3_DLLClass );}
#line 111 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
ulFirst  = offsetof  (CSunMoon  , m_epSkyHorizon );
#line 112 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(slPropertyOffset  == ulFirst ){return IsDerivedFromClass  (penTarget  , & CModelHolder3_DLLClass );}
#line 114 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
ulFirst  = offsetof  (CSunMoon  , m_epHaze );
#line 115 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(slPropertyOffset  == ulFirst ){return IsDerivedFromClass  (penTarget  , & CHazeMarker_DLLClass );}
#line 117 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
ulFirst  = offsetof  (CSunMoon  , m_epFog );
#line 118 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(slPropertyOffset  == ulFirst ){return IsDerivedFromClass  (penTarget  , & CFogMarker_DLLClass );}
#line 120 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
ulFirst  = offsetof  (CSunMoon  , m_epSunModel );
#line 121 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(slPropertyOffset  == ulFirst ){return (IsDerivedFromClass  (penTarget  , & CModelHolder3_DLLClass ) || IsDerivedFromClass  (penTarget  , & CModelHolder2_DLLClass ));}
#line 123 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
ulFirst  = offsetof  (CSunMoon  , m_epMoonModel );
#line 124 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(slPropertyOffset  == ulFirst ){return (IsDerivedFromClass  (penTarget  , & CModelHolder3_DLLClass ) || IsDerivedFromClass  (penTarget  , & CModelHolder2_DLLClass ));}
#line 126 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
return CEntity  :: IsTargetValid  (slPropertyOffset  , penTarget );
#line 127 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}

#line 128 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
CEnvironmentParticlesHolder * CSunMoon::GetEPH() 
#line 129 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 130 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
CWorld  * pWorld  = this  -> GetWorld  ();
#line 131 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(pWorld  != NULL )
#line 132 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 133 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
CBackgroundViewer  * pBV  = (CBackgroundViewer  *) (CEntity  *) (pWorld  -> wo_penBackgroundViewer );
#line 134 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(pBV  != NULL )
#line 135 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 136 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
CWorldSettingsController  * pWSC  = (CWorldSettingsController  *) (CEntity  *) (pBV  -> m_penWorldSettingsController );
#line 137 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(pWSC  != NULL )
#line 138 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 139 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
return (CEnvironmentParticlesHolder  *) (CEntity  *) (pWSC  -> m_penEnvPartHolder );
#line 140 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 141 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 142 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 143 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
return NULL ;
#line 144 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}

#line 145 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
CLight * CSunMoon::GetLight() 
#line 146 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 147 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if((CEntity  *) m_epLight  != NULL )
#line 148 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 149 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
return (CLight  *) (CEntity  *) m_epLight ;
#line 150 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 151 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
return NULL ;
#line 152 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}

#line 153 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
CModelHolder3 * CSunMoon::GetSky() 
#line 154 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 155 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if((CEntity  *) m_epSky  != NULL )
#line 156 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 157 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
return (CModelHolder3  *) (CEntity  *) m_epSky ;
#line 158 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 159 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
return NULL ;
#line 160 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}

#line 161 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
CModelHolder3 * CSunMoon::GetSkyHorizon() 
#line 162 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 163 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if((CEntity  *) m_epSkyHorizon  != NULL )
#line 164 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 165 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
return (CModelHolder3  *) (CEntity  *) m_epSkyHorizon ;
#line 166 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 167 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
return NULL ;
#line 168 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}

#line 169 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
CHazeMarker * CSunMoon::GetHaze() 
#line 170 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 171 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if((CEntity  *) m_epHaze  != NULL )
#line 172 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 173 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
return (CHazeMarker  *) (CEntity  *) m_epHaze ;
#line 174 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 175 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
return NULL ;
#line 176 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}

#line 177 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
CFogMarker * CSunMoon::GetFog() 
#line 178 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 179 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if((CEntity  *) m_epFog  != NULL )
#line 180 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 181 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
return (CFogMarker  *) (CEntity  *) m_epFog ;
#line 182 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 183 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
return NULL ;
#line 184 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}

#line 185 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
void CSunMoon::SetSunModelColor(COLOR col) 
#line 186 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 187 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if((CEntity  *) m_epSunModel  != NULL )
#line 188 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 189 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(IsDerivedFromClass  (m_epSunModel  , & CModelHolder3_DLLClass ))
#line 190 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 191 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(m_epSunModel  -> GetModelInstance  ())
#line 192 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 193 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_epSunModel  -> GetModelInstance  () -> SetModelColor  (col );
#line 194 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
((CModelHolder3  *) (CEntity  *) m_epSunModel ) -> m_colModelColor  = col ;
#line 195 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 196 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 197 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
else 
#line 198 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 199 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(m_epSunModel  -> GetModelObject  ())
#line 200 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 201 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_epSunModel  -> GetModelObject  () -> mo_colBlendColor  = col ;
#line 202 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
((CModelHolder2  *) (CEntity  *) m_epSunModel ) -> m_colModelColor  = col ;
#line 203 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 204 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 205 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 206 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}

#line 207 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
void CSunMoon::SetMoonModelColor(COLOR col) 
#line 208 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 209 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if((CEntity  *) m_epMoonModel  != NULL )
#line 210 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 211 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(IsDerivedFromClass  (m_epMoonModel  , & CModelHolder3_DLLClass ))
#line 212 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 213 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(m_epMoonModel  -> GetModelInstance  ())
#line 214 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 215 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_epMoonModel  -> GetModelInstance  () -> SetModelColor  (col );
#line 216 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
((CModelHolder3  *) (CEntity  *) m_epMoonModel ) -> m_colModelColor  = col ;
#line 217 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 218 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 219 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
else 
#line 220 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 221 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(m_epMoonModel  -> GetModelObject  ())
#line 222 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 223 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_epMoonModel  -> GetModelObject  () -> mo_colBlendColor  = col ;
#line 224 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
((CModelHolder2  *) (CEntity  *) m_epMoonModel ) -> m_colModelColor  = col ;
#line 225 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 226 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 227 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 228 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}

#line 230 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
void CSunMoon::SetLensFlare(LensFlareType lft) 
#line 231 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 232 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(GetLight  () == NULL ){return ;}
#line 234 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
CLightSource  lsNew ;
#line 235 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
GetLight  () -> SetupLightSource  (lsNew );
#line 236 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
switch(lft )
#line 237 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 238 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
case LFT_NONE : 
#line 239 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
lsNew  . ls_plftLensFlare  = NULL ;
#line 240 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
break ;
#line 241 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
case LFT_STANDARD : 
#line 242 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
lsNew  . ls_plftLensFlare  = & _lftStandard ;
#line 243 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
break ;
#line 244 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
case LFT_STANDARD_REFLECTIONS : 
#line 245 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
lsNew  . ls_plftLensFlare  = & _lftStandardReflections ;
#line 246 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
break ;
#line 247 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
case LFT_YELLOW_STAR_RED_RING : 
#line 248 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
lsNew  . ls_plftLensFlare  = & _lftYellowStarRedRing ;
#line 249 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
break ;
#line 250 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
case LFT_WHITE_GLOW_STAR_RED_RING : 
#line 251 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteGlowStarRedRing ;
#line 252 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
break ;
#line 253 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
case LFT_WHITE_GLOW_STAR : 
#line 254 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteGlowStar ;
#line 255 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
break ;
#line 256 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
case LFT_WHITE_STAR_RED_RING_STREAKS : 
#line 257 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteStarRedRingStreaks ;
#line 258 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
break ;
#line 259 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
case LFT_WHITE_STAR_RED_REFLECTIONS : 
#line 260 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteStarRedReflections ;
#line 261 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
break ;
#line 262 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
case LFT_BLUE_STAR_BLUE_REFLECTIONS : 
#line 263 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
lsNew  . ls_plftLensFlare  = & _lftBlueStarBlueReflections ;
#line 264 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
break ;
#line 268 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
case LFT_WHITE_GLOW_STAR_RED_RING_FAR : 
#line 269 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
lsNew  . ls_plftLensFlare  = & _lftYellowStarRedRingFar ;
#line 270 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
break ;
#line 271 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
case LFT_WHITE_GLOW_FAR : 
#line 272 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteGlowFar ;
#line 273 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
break ;
#line 274 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
case LFT_WHITE_GLOW_STAR_NG : 
#line 275 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
lsNew  . ls_plftLensFlare  = & _lftWhiteGlowStarNG ;
#line 276 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
break ;
#line 277 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 278 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
GetLight  () -> m_lsLightSource  . SetLightSourceWithNoDiscarding  (lsNew );
#line 279 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}

#line 281 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
COLOR CSunMoon::GetCurrentSkyAniColor(COLOR colBase) 
#line 282 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 283 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(m_aoSkyColAni  . GetData  () != NULL )
#line 284 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 285 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
UBYTE  ubR  , ubG  , ubB ;
#line 286 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
ColorToRGB  (colBase  , ubR  , ubG  , ubB );
#line 287 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
FLOAT fRatio ;
#line 288 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
COLOR col0  , col1 ;
#line 289 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
UBYTE  ubMR  , ubMG  , ubMB ;
#line 290 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_aoSkyColAni  . GetFrame  ((SLONG  &) col0  , (SLONG  &) col1  , fRatio );
#line 291 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
LerpColor  (col0  , col1  , fRatio  , ubMR  , ubMG  , ubMB );
#line 292 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
ubR  = (((((SLONG ) ubR ) << 8) | ubR ) * ((((SLONG ) ubMR ) << 8) | ubMR )) >> 24;
#line 293 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
ubG  = (((((SLONG ) ubG ) << 8) | ubG ) * ((((SLONG ) ubMG ) << 8) | ubMG )) >> 24;
#line 294 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
ubB  = (((((SLONG ) ubB ) << 8) | ubB ) * ((((SLONG ) ubMB ) << 8) | ubMB )) >> 24;
#line 295 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
colBase  = RGBToColor  (ubR  , ubG  , ubB ) | ((colBase  & CT_AMASK ) >> CT_ASHIFT );
#line 296 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 297 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
return colBase ;
#line 298 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}

#line 299 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
COLOR CSunMoon::GetCurrentSkyAniColor() 
#line 300 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 301 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
return GetCurrentSkyAniColor  (C_WHITE_OPAQUE );
#line 302 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}

#line 303 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
CAnimData * CSunMoon::GetAnimData(SLONG slPropertyOffset) 
#line 304 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 305 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(slPropertyOffset  == offsetof  (CSunMoon  , m_iSkyColAni ))
#line 306 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 307 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
return m_aoSkyColAni  . GetData  ();
#line 308 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 309 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
else 
#line 310 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 311 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
return CEntity  :: GetAnimData  (slPropertyOffset );
#line 312 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 313 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}

#line 315 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
void CSunMoon::SetLightPlacement3D() 
#line 316 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 317 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(GetLight  () == NULL ){return ;}
#line 319 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
DOUBLE  tmOffset  = GAMETIME_ONEDAY_SECOND  - GAMETIME_MORNING_SECOND ;
#line 320 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
DOUBLE  dGWTSecondFromMorning  = g_fGWTime  + tmOffset ;
#line 323 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(dGWTSecondFromMorning  > GAMETIME_ONEDAY_SECOND )
#line 324 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 325 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
dGWTSecondFromMorning  -= GAMETIME_ONEDAY_SECOND  * (INDEX) (dGWTSecondFromMorning  / GAMETIME_ONEDAY_SECOND );
#line 326 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 327 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
CPlacement3D place ;
#line 328 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
FLOAT theta  = 0.0f;
#line 331 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(dGWTSecondFromMorning  < GAMETIME_NOONDAY_SECOND )
#line 332 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 333 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
theta  = PI  * dGWTSecondFromMorning  / (FLOAT) GAMETIME_NOONDAY_SECOND ;
#line 334 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(m_bNoon )
#line 335 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 336 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
SendToTarget  (m_epMorningTarget  , m_eetMorningEvent  , this );
#line 337 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
SetLensFlare  (m_lftSun );
#line 338 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_bNoon  = FALSE ;
#line 339 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_bNight  = TRUE ;
#line 340 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
SetSunModelColor  (0xFFFFFFFF);
#line 341 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
SetMoonModelColor  (0x00000000);
#line 342 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 343 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 345 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
else 
#line 346 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 347 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
theta  = PI  - PI  * (dGWTSecondFromMorning  - GAMETIME_NOONDAY_SECOND ) / (FLOAT) GAMETIME_NIGHT_SECOND ;
#line 348 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(m_bNight )
#line 349 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 350 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
SendToTarget  (m_epEveningTarget  , m_eetEveningEvent  , this );
#line 351 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
SetLensFlare  (m_lftMoon );
#line 352 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_bNoon  = TRUE ;
#line 353 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_bNight  = FALSE ;
#line 354 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
SetSunModelColor  (0x00000000);
#line 355 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
SetMoonModelColor  (0xFFFFFFFF);
#line 356 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 357 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 359 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
place  . pl_PositionVector  (1) = m_fLength  * cos  (theta );
#line 360 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
place  . pl_PositionVector  (2) = m_fHeight  * sin  (theta );
#line 361 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
place  . pl_PositionVector  (3) = 0;
#line 362 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
place  . pl_OrientationAngle  (1) = 270.0f;
#line 363 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
place  . pl_OrientationAngle  (2) = 180.0f + theta  * 180.0f / PI ;
#line 364 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
place  . pl_OrientationAngle  (3) = 0.0f;
#line 366 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
CPlacement3D placeOld  = this  -> en_plPlacement ;
#line 367 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
CPlacement3D placeZero  (FLOAT3D (0 , 0 , 0) , ANGLE3D (0 , 0 , 0));
#line 369 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
GetLight  () -> SetParent  (NULL );
#line 370 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
this  -> SetPlacement  (placeZero );
#line 371 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
GetLight  () -> SetPlacement  (place );
#line 372 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
GetLight  () -> SetParent  (this );
#line 374 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
this  -> SetPlacement  (placeOld );
#line 376 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}

#line 378 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
void CSunMoon::SetCurrentColor() 
#line 379 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 380 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
FLOAT fGWTime  = g_fGWTime ;
#line 381 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
DOUBLE  rwtime  = - g_fGWTime  * GWTOneSec2RWTSec ;
#line 382 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
TIME  tmNow  = _pTimer  -> CurrentTick  () + _pTimer  -> GetLerpFactor  () * _pTimer  -> TickQuantum ;
#line 383 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
DOUBLE  rwOffsetTime  = rwtime  + tmNow ;
#line 385 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(GetLight  ())
#line 386 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 387 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
GetLight  () -> m_aoLightAnimation  . ResetAnim  ();
#line 388 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
GetLight  () -> m_aoAmbientLightAnimation  . ResetAnim  ();
#line 389 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
GetLight  () -> m_aoLightAnimation  . ao_tmAnimStart  = rwOffsetTime ;
#line 390 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
GetLight  () -> m_aoAmbientLightAnimation  . ao_tmAnimStart  = rwOffsetTime ;
#line 391 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
GetLight  () -> m_lsLightSource  . ls_colAmbient  = MulColors  (GetLight  () -> m_colAmbient  , g_colWeather );
#line 392 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
g_colNewGameShadeColor  = AddColors  (
#line 393 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
GetLight  () -> m_lsLightSource  . GetLightAmbient  () 
#line 394 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
, GetLight  () -> m_lsLightSource  . GetLightColor  ()) | CT_OPAQUE ;
#line 395 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(GetSkyHorizon  ())
#line 396 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 397 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
ENGINE_API  INDEX g_iUseBloom ;
#line 398 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
static COLOR col2nd  = 0x9E9E9EFF;
#line 399 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
static COLOR col1st  = 0xA5A5A5FF;
#line 400 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
COLOR color  = g_iUseBloom  == 0 
#line 401 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
? g_colNewGameShadeColor  
#line 402 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
: MulColors  (g_colNewGameShadeColor  , g_iUseBloom  > 2 ? col2nd  : col1st );
#line 403 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
GetSkyHorizon  () -> GetModelInstance  () -> SetModelColor  (
#line 404 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
MulColors  (GetSkyHorizon  () -> m_colModelColor  , color )
#line 405 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
);
#line 406 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
GetSkyHorizon  () -> m_aShadingDirection  = GetLight  () -> en_plPlacement  . pl_OrientationAngle ;
#line 407 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
AnglesToDirectionVector  (GetSkyHorizon  () -> m_aShadingDirection  , GetSkyHorizon  () -> m_vShadingDirection );
#line 409 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 410 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(GetHaze  ())
#line 411 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 412 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
GetHaze  () -> m_colBase  = MulColors  (m_colHazeDefault  , g_colNewGameShadeColor );
#line 413 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 414 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(GetFog  ())
#line 415 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 416 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
GetFog  () -> m_colColor  = MulColors  (m_colFogDefault  , g_colNewGameShadeColor );
#line 417 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 418 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 419 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(m_aoSkyColAni  . GetData  () != NULL )
#line 420 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 421 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_aoSkyColAni  . ResetAnim  ();
#line 422 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_aoSkyColAni  . ao_tmAnimStart  = rwOffsetTime ;
#line 423 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
COLOR colSky  = GetCurrentSkyAniColor  (g_colWeather );
#line 424 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(GetSky  ())
#line 425 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 426 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
GetSky  () -> GetModelInstance  () -> SetModelColor  (
#line 427 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
MulColors  (GetSky  () -> m_colModelColor  , colSky )
#line 428 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
);
#line 429 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 430 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 431 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}

#line 434 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
void CSunMoon::LightProcess() 
#line 435 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 436 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(m_bActive )
#line 437 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 438 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
SetLightPlacement3D  ();
#line 439 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
SetCurrentColor  ();
#line 440 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 441 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
BOOL CSunMoon::
#line 445 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
Main(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CSunMoon_Main
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CSunMoon::Main expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 448 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
InitModelHolder  ();
#line 450 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
g_colWeather  = C_WHITE_OPAQUE ;
#line 451 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
FLOAT fRWDaySecond  = (FLOAT) GAMETIME_ONEDAY_SECOND  * GWTOneSec2RWTSec ;
#line 453 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
try 
#line 454 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 455 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_aoSkyColAni  . SetData_t  (m_fnmColAniFile );
#line 456 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 457 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
catch  (char  * strError )
#line 458 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 459 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
WarningMessage  (TRANS  ("Cannot load '%s': %s") , (CTString &) m_fnmColAniFile  , strError );
#line 460 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_fnmColAniFile  = "";
#line 461 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 462 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(m_aoSkyColAni  . GetData  () != NULL )
#line 463 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 464 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_aoSkyColAni  . PlayAnim  (m_iSkyColAni  , AOF_LOOPING );
#line 465 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_aoSkyColAni  . ao_tmAnimStart  = 0;
#line 466 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_aoSkyColAni  . GetData  () -> SetSpeed  (
#line 467 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_iSkyColAni  
#line 468 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
, fRWDaySecond  / (FLOAT) m_aoSkyColAni  . GetFramesInCurrentAnim  ()
#line 469 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
);
#line 470 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 472 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_fFadeTime  = 0.0f;
#line 473 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_fAllFadeTime  = 1.0f;
#line 474 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_dPrevGWTime  = g_fGWTime ;
#line 475 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_bNoon  = TRUE ;
#line 476 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_bNight  = TRUE ;
#line 478 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
CLight  * pLight  = GetLight  ();
#line 479 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(pLight  != NULL )
#line 480 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 481 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
pLight  -> SetParent  (this );
#line 482 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_plftDefault  = pLight  -> m_lsLightSource  . ls_plftLensFlare ;
#line 483 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(pLight  -> m_aoLightAnimation  . GetData  () != NULL )
#line 484 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 485 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
pLight  -> m_aoLightAnimation  . GetData  () -> SetSpeed  (
#line 486 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
pLight  -> m_iLightAnimation  
#line 487 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
, fRWDaySecond  / (FLOAT) pLight  -> m_aoLightAnimation  . GetFramesInCurrentAnim  ()
#line 488 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
);
#line 489 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 490 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(pLight  -> m_aoAmbientLightAnimation  . GetData  () != NULL )
#line 491 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 492 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
pLight  -> m_aoAmbientLightAnimation  . GetData  () -> SetSpeed  (
#line 493 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
pLight  -> m_iAmbientLightAnimation  
#line 494 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
, fRWDaySecond  / (FLOAT) pLight  -> m_aoAmbientLightAnimation  . GetFramesInCurrentAnim  ()
#line 495 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
);
#line 496 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 497 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 498 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_strName  . RemovePrefix  ("SunMoon ");
#line 499 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_strName  = CTString ("SunMoon ") + m_strName ;
#line 500 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(pLight  != NULL )
#line 501 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 502 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
pLight  -> m_strName  . RemovePrefix  ("SunMoon ");
#line 503 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
pLight  -> m_strName  = CTString ("SunMoon ") + pLight  -> m_strName ;
#line 504 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 506 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(GetSky  ())
#line 507 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 508 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
GetSky  () -> GetModelInstance  () -> SetModelColor  (
#line 509 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
GetCurrentSkyAniColor  (GetSky  () -> m_colModelColor )
#line 510 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
);
#line 511 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 513 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
Jump(STATE_CURRENT, STATE_CSunMoon_MainLoop, TRUE, EVoid());return TRUE; ASSERT(FALSE); return TRUE;};BOOL CSunMoon::
#line 516 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
FadeInRain(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CSunMoon_FadeInRain
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CSunMoon::FadeInRain expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 518 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_bNoon  = TRUE ;
#line 519 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_bNight  = TRUE ;
#line 521 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
g_bBadWeather  = TRUE ;
#line 522 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_dPrevGWTime  = g_fGWTime ;
#line 523 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
g_colWeather  = C_WHITE_OPAQUE ;
#line 524 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
LightProcess  ();
#line 526 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
Jump(STATE_CURRENT,0x03e90003, FALSE, EInternal());return TRUE;}BOOL CSunMoon::H0x03e90003_FadeInRain_03(const CEntityEvent &__eeInput)
#line 527 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x03e90003
if(!(m_fFadeTime  >= 0.0f)){ Jump(STATE_CURRENT,0x03e90004, FALSE, EInternal());return TRUE;}
#line 528 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
FLOAT percent  = Clamp  (1.0f - m_fFadeTime  / m_fAllFadeTime  , 0.0f , 1.0f);
#line 529 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
g_colWeather  = LerpColor  (C_WHITE_OPAQUE  , m_colRainAmbient  , percent ) | CT_OPAQUE ;
#line 531 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
LightProcess  ();
#line 533 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_fFadeTime  -= (g_fGWTime  - m_dPrevGWTime );
#line 534 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_dPrevGWTime  = g_fGWTime ;
#line 535 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
SetTimerAfter(0.1f);
Jump(STATE_CURRENT, 0x03e90001, FALSE, EBegin());return TRUE;}BOOL CSunMoon::H0x03e90001_FadeInRain_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x03e90001
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x03e90002, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CSunMoon::H0x03e90002_FadeInRain_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x03e90002
;Jump(STATE_CURRENT,0x03e90003, FALSE, EInternal());return TRUE;
#line 536 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}BOOL CSunMoon::H0x03e90004_FadeInRain_04(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x03e90004

#line 537 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
g_colWeather  = m_colRainAmbient ;
#line 538 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_bNoon  = m_bNight  = FALSE ;
#line 539 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
SetLensFlare  (LFT_NONE );
#line 540 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
Jump(STATE_CURRENT, STATE_CSunMoon_MainLoop, TRUE, EVoid());return TRUE;
#line 541 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
Return(STATE_CURRENT,EVoid());
#line 541 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CSunMoon::
#line 543 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
FadeOutRain(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CSunMoon_FadeOutRain
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CSunMoon::FadeOutRain expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 545 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_bNoon  = TRUE ;
#line 546 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_bNight  = TRUE ;
#line 548 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
g_bBadWeather  = FALSE ;
#line 549 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_dPrevGWTime  = g_fGWTime ;
#line 550 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
g_colWeather  = m_colRainAmbient ;
#line 551 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
LightProcess  ();
#line 553 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
Jump(STATE_CURRENT,0x03e90008, FALSE, EInternal());return TRUE;}BOOL CSunMoon::H0x03e90008_FadeOutRain_03(const CEntityEvent &__eeInput)
#line 554 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x03e90008
if(!(m_fFadeTime  >= 0.0f)){ Jump(STATE_CURRENT,0x03e90009, FALSE, EInternal());return TRUE;}
#line 555 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
FLOAT percent  = Clamp  (1.0f - m_fFadeTime  / m_fAllFadeTime  , 0.0f , 1.0f);
#line 556 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
g_colWeather  = LerpColor  (m_colRainAmbient  , C_WHITE_OPAQUE  , percent ) | CT_OPAQUE ;
#line 558 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
LightProcess  ();
#line 560 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_fFadeTime  -= (g_fGWTime  - m_dPrevGWTime );
#line 561 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_dPrevGWTime  = g_fGWTime ;
#line 562 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
SetTimerAfter(0.1f);
Jump(STATE_CURRENT, 0x03e90006, FALSE, EBegin());return TRUE;}BOOL CSunMoon::H0x03e90006_FadeOutRain_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x03e90006
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x03e90007, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CSunMoon::H0x03e90007_FadeOutRain_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x03e90007
;Jump(STATE_CURRENT,0x03e90008, FALSE, EInternal());return TRUE;
#line 563 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}BOOL CSunMoon::H0x03e90009_FadeOutRain_04(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x03e90009

#line 564 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
g_colWeather  = C_WHITE_OPAQUE ;
#line 565 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_bNoon  = m_bNight  = TRUE ;
#line 566 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
Jump(STATE_CURRENT, STATE_CSunMoon_MainLoop, TRUE, EVoid());return TRUE;
#line 567 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
Return(STATE_CURRENT,EVoid());
#line 567 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
return TRUE; ASSERT(FALSE); return TRUE;};BOOL CSunMoon::
#line 569 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
GoodWeather(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CSunMoon_GoodWeather
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CSunMoon::GoodWeather expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 571 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_bNoon  = TRUE ;
#line 572 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_bNight  = TRUE ;
#line 574 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
Jump(STATE_CURRENT,0x03e9000d, FALSE, EInternal());return TRUE;}BOOL CSunMoon::H0x03e9000d_GoodWeather_03(const CEntityEvent &__eeInput)
#line 575 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x03e9000d
if(!(TRUE )){ Jump(STATE_CURRENT,0x03e9000e, FALSE, EInternal());return TRUE;}
#line 576 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(GetLight  ())
#line 577 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 578 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
LightProcess  ();
#line 579 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 580 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
SetTimerAfter(0.100f);
Jump(STATE_CURRENT, 0x03e9000b, FALSE, EBegin());return TRUE;}BOOL CSunMoon::H0x03e9000b_GoodWeather_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x03e9000b
switch(__eeInput.ee_slEvent) {case EVENTCODE_EBegin: return TRUE;case EVENTCODE_ETimer: Jump(STATE_CURRENT,0x03e9000c, FALSE, EInternal()); return TRUE;default: return FALSE; }}BOOL CSunMoon::H0x03e9000c_GoodWeather_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x03e9000c
;Jump(STATE_CURRENT,0x03e9000d, FALSE, EInternal());return TRUE;
#line 581 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}BOOL CSunMoon::H0x03e9000e_GoodWeather_04(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x03e9000e
 ASSERT(FALSE); return TRUE;};BOOL CSunMoon::
#line 584 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
MainLoop(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CSunMoon_MainLoop
	ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CSunMoon::MainLoop expects 'EVoid' as input!");	const EVoid &e = (const EVoid &)__eeInput;
#line 586 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_dPrevGWTime  = g_fGWTime ;
#line 587 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_bNoon  = TRUE ;
#line 588 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_bNight  = TRUE ;
#line 589 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
LightProcess  ();
#line 591 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
Jump(STATE_CURRENT,0x03e90012, FALSE, EInternal());return TRUE;}BOOL CSunMoon::H0x03e90012_MainLoop_03(const CEntityEvent &__eeInput)
#line 592 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x03e90012
if(!(TRUE )){ Jump(STATE_CURRENT,0x03e90013, FALSE, EInternal());return TRUE;}
#line 593 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
LightProcess  ();
#line 594 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
SetTimerAt(THINKTIME_NEVER);
Jump(STATE_CURRENT, 0x03e90010, FALSE, EBegin());return TRUE;}BOOL CSunMoon::H0x03e90010_MainLoop_01(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT 0x03e90010
switch(__eeInput.ee_slEvent)
#line 595 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{case(EVENTCODE_EBegin):{const EBegin&e= (EBegin&)__eeInput;
Call(STATE_CURRENT, STATE_CSunMoon_GoodWeather, TRUE, EVoid());return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_EActivate):{const EActivate&e= (EActivate&)__eeInput;
m_bActive  = TRUE ;return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_EDeactivate):{const EDeactivate&e= (EDeactivate&)__eeInput;
m_bActive  = FALSE ;return TRUE;}ASSERT(FALSE);break;case(EVENTCODE_EStart):{const EStart&e= (EStart&)__eeInput;

#line 600 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(GetEPH  () != NULL )
#line 601 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 602 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_fAllFadeTime  = m_fFadeTime  = GetEPH  () -> m_fRainAppearLen  * RWTOneSec2GWTSec ;
#line 603 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 604 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
else 
#line 605 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 606 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_fAllFadeTime  = m_fFadeTime  = 1.0f * RWTOneSec2GWTSec ;
#line 607 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 608 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_bWeatherSun  = TRUE ;
#line 609 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(GetLight  () != NULL  && g_colWeather  == C_WHITE_OPAQUE )
#line 610 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 611 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
Jump(STATE_CURRENT, STATE_CSunMoon_FadeInRain, TRUE, EVoid());return TRUE;
#line 612 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 613 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
else 
#line 614 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 615 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
UnsetTimer();Jump(STATE_CURRENT,0x03e90011, FALSE, EInternal());return TRUE;
#line 616 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 617 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}ASSERT(FALSE);break;case(EVENTCODE_EStop):{const EStop&e= (EStop&)__eeInput;

#line 619 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(GetEPH  () != NULL )
#line 620 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 621 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_fAllFadeTime  = m_fFadeTime  = GetEPH  () -> m_fRainAppearLen  * RWTOneSec2GWTSec ;
#line 622 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 623 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
else 
#line 624 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 625 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_fAllFadeTime  = m_fFadeTime  = 1.0f * RWTOneSec2GWTSec ;
#line 626 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 627 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_bWeatherSun  = FALSE ;
#line 628 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
if(GetLight  () != NULL  && g_colWeather  == m_colRainAmbient )
#line 629 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 630 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
Jump(STATE_CURRENT, STATE_CSunMoon_FadeOutRain, TRUE, EVoid());return TRUE;
#line 631 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 632 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
else 
#line 633 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
{
#line 634 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
UnsetTimer();Jump(STATE_CURRENT,0x03e90011, FALSE, EInternal());return TRUE;
#line 635 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}
#line 636 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}ASSERT(FALSE);break;case(EVENTCODE_ETrigger):{const ETrigger&et= (ETrigger&)__eeInput;
UnsetTimer();Jump(STATE_CURRENT,0x03e90011, FALSE, EInternal());return TRUE;}ASSERT(FALSE);break;default: return FALSE; break;
#line 638 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}return TRUE;}BOOL CSunMoon::H0x03e90011_MainLoop_02(const CEntityEvent &__eeInput){
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x03e90011
;
#line 639 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
m_dPrevGWTime  = g_fGWTime ;Jump(STATE_CURRENT,0x03e90012, FALSE, EInternal());return TRUE;
#line 640 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
}BOOL CSunMoon::H0x03e90013_MainLoop_04(const CEntityEvent &__eeInput) {
ASSERT(__eeInput.ee_slEvent==EVENTCODE_EInternal);
#undef STATE_CURRENT
#define STATE_CURRENT 0x03e90013

#line 641 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/SunMoon.es"
int  a  = 0; ASSERT(FALSE); return TRUE;};