/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#ifndef _Terrain_INCLUDED
#define _Terrain_INCLUDED 1
extern "C" DECL_DLL CDLLEntityClass CTerrainEntity_DLLClass;
class CTerrainEntity : public CEntity {
public:
	DECL_DLL virtual void SetDefaultProperties(void);
#define  STATE_CTerrainEntity_Main 1
	BOOL 
#line 14 "C:/Users/Postman/Documents/LastChaos/Games/LastChaos2018/client/src/EntitiesMP/Terrain.es"
Main(const CEntityEvent &__eeInput);
};
#endif // _Terrain_INCLUDED
