[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$SourceDirectory,

    [Parameter(Mandatory = $true)]
    [string]$OutputHeader,

    [string]$WindowsSdkVersion = '',

    [string]$DxcPath = ''
)

$ErrorActionPreference = 'Stop'

function Resolve-DxcPath {
    param(
        [string]$ExplicitPath,
        [string]$SdkVersion
    )

    if (-not [string]::IsNullOrWhiteSpace($ExplicitPath)) {
        $resolved = [IO.Path]::GetFullPath($ExplicitPath)
        if (-not (Test-Path -LiteralPath $resolved)) {
            throw "No se encontró DXC en '$resolved'."
        }
        return $resolved
    }

    $sdkBin = Join-Path ${env:ProgramFiles(x86)} 'Windows Kits\10\bin'
    $normalizedVersion = $SdkVersion.Trim().TrimEnd('\')
    if (-not [string]::IsNullOrWhiteSpace($normalizedVersion)) {
        $candidate = Join-Path $sdkBin "$normalizedVersion\x64\dxc.exe"
        if (Test-Path -LiteralPath $candidate) {
            return $candidate
        }
    }

    $candidates = Get-ChildItem -LiteralPath $sdkBin -Directory |
        ForEach-Object {
            $candidate = Join-Path $_.FullName 'x64\dxc.exe'
            if (Test-Path -LiteralPath $candidate) {
                [pscustomobject]@{
                    Version = [version]$_.Name
                    Path = $candidate
                }
            }
        } |
        Sort-Object Version -Descending
    if ($null -eq $candidates -or $candidates.Count -eq 0) {
        throw 'No se encontró dxc.exe en ningún Windows SDK instalado.'
    }
    return $candidates[0].Path
}

function Format-ByteArray {
    param([byte[]]$Bytes)

    $lines = [Collections.Generic.List[string]]::new()
    for ($offset = 0; $offset -lt $Bytes.Length; $offset += 12) {
        $count = [Math]::Min(12, $Bytes.Length - $offset)
        $values = for ($index = 0; $index -lt $count; ++$index) {
            '0x{0:X2}' -f $Bytes[$offset + $index]
        }
        $lines.Add("    $($values -join ', '),")
    }
    return $lines
}

$sourceRoot = [IO.Path]::GetFullPath($SourceDirectory)
$headerPath = [IO.Path]::GetFullPath($OutputHeader)
$headerDirectory = Split-Path -Parent $headerPath
[IO.Directory]::CreateDirectory($headerDirectory) | Out-Null
$compiler = Resolve-DxcPath -ExplicitPath $DxcPath `
    -SdkVersion $WindowsSdkVersion

$manifest = @(
    @{ Name = 'NativeValidationVS'; File = 'NativeValidation.hlsl'; Entry = 'VSMain'; Target = 'vs_6_0' }
    @{ Name = 'NativeValidationPS'; File = 'NativeValidation.hlsl'; Entry = 'PSMain'; Target = 'ps_6_0' }
    @{ Name = 'Textured2DVS'; File = 'Textured2D.hlsl'; Entry = 'VSMain'; Target = 'vs_6_0' }
    @{ Name = 'Textured2DPS'; File = 'Textured2D.hlsl'; Entry = 'PSMain'; Target = 'ps_6_0' }
    @{ Name = 'TexturedAlphaTest2DPS'; File = 'TexturedAlphaTest2D.hlsl'; Entry = 'PSMain'; Target = 'ps_6_0' }
    @{ Name = 'BloomVS'; File = 'Bloom.hlsl'; Entry = 'VSMain'; Target = 'vs_6_0' }
    @{ Name = 'BloomDownsamplePS'; File = 'Bloom.hlsl'; Entry = 'PSDownsample'; Target = 'ps_6_0' }
    @{ Name = 'BloomBlurPS'; File = 'Bloom.hlsl'; Entry = 'PSBlur'; Target = 'ps_6_0' }
    @{ Name = 'BloomCompositePS'; File = 'Bloom.hlsl'; Entry = 'PSComposite'; Target = 'ps_6_0' }
    @{ Name = 'Legacy3DVS'; File = 'Legacy3D.hlsl'; Entry = 'VSMain'; Target = 'vs_6_0' }
    @{ Name = 'Legacy3DPS'; File = 'Legacy3D.hlsl'; Entry = 'PSMain'; Target = 'ps_6_0' }
    @{ Name = 'RigidLit3DVS'; File = 'RigidLit3D.hlsl'; Entry = 'VSMain'; Target = 'vs_6_0' }
    @{ Name = 'RigidLit3DPS'; File = 'RigidLit3D.hlsl'; Entry = 'PSMain'; Target = 'ps_6_0' }
    @{ Name = 'LegacyMaterial3DVS'; File = 'LegacyMaterial3D.hlsl'; Entry = 'VSMain'; Target = 'vs_6_0' }
    @{ Name = 'LegacyMaterial3DPS'; File = 'LegacyMaterial3D.hlsl'; Entry = 'PSMain'; Target = 'ps_6_0' }
)

$workDirectory = Join-Path $headerDirectory 'dxil'
[IO.Directory]::CreateDirectory($workDirectory) | Out-Null
$header = [Collections.Generic.List[string]]::new()
$header.Add('// Generated by scripts/compile-dx12-shaders.ps1. Do not edit.')
$header.Add('#ifndef SE_INCL_DIRECTX12NATIVESHADERBLOBS_GENERATED_H')
$header.Add('#define SE_INCL_DIRECTX12NATIVESHADERBLOBS_GENERATED_H')
$header.Add('')
$header.Add('namespace DirectX12GeneratedShaders')
$header.Add('{')

foreach ($shader in $manifest) {
    $sourcePath = Join-Path $sourceRoot $shader.File
    if (-not (Test-Path -LiteralPath $sourcePath)) {
        throw "Falta la fuente HLSL '$sourcePath'."
    }
    $blobPath = Join-Path $workDirectory "$($shader.Name).dxil"
    $arguments = @(
        '-nologo'
        '-Ges'
        '-HV', '2018'
        '-O3'
        '-Qstrip_debug'
        '-Qstrip_reflect'
        '-T', $shader.Target
        '-E', $shader.Entry
        '-Fo', $blobPath
        $sourcePath
    )
    & $compiler @arguments
    if ($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $blobPath)) {
        throw (
            "DXC falló para $($shader.File)/$($shader.Entry) " +
            "($($shader.Target))."
        )
    }

    $bytes = [IO.File]::ReadAllBytes($blobPath)
    if ($bytes.Length -eq 0) {
        throw "DXC produjo un blob vacío para '$($shader.Name)'."
    }
    $header.Add("static const unsigned char k$($shader.Name)[] = {")
    foreach ($line in (Format-ByteArray -Bytes $bytes)) {
        $header.Add($line)
    }
    $header.Add('};')
    $header.Add('')
}

$header.Add('}')
$header.Add('')
$header.Add('#endif')
$header.Add('')

$encoding = [Text.UTF8Encoding]::new($false)
$content = $header -join [Environment]::NewLine
$temporaryHeader = "$headerPath.tmp"
[IO.File]::WriteAllText($temporaryHeader, $content, $encoding)
if ((Test-Path -LiteralPath $headerPath) -and
    [IO.File]::ReadAllText($headerPath) -ceq $content) {
    Remove-Item -LiteralPath $temporaryHeader
}
else {
    Move-Item -LiteralPath $temporaryHeader -Destination $headerPath -Force
}

Write-Host (
    "DX12 shaders: $($manifest.Count) blobs DXIL generados con " +
    "'$compiler'."
)
