from __future__ import annotations

import argparse
import ctypes
import sys
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
TOOL_ROOT = REPOSITORY_ROOT / "tools" / "dx12_shader_inventory"
sys.path.insert(0, str(TOOL_ROOT))

from shader_inventory.internal_programs import load_internal_program_shaders
from shader_inventory.legacy_fingerprints import build_exact_runtime_inventory
from shader_inventory.manifests import load_manifests
from shader_inventory.runtime_catalog import load_runtime_catalog
from shader_inventory.shader_host import (
    ShaderMetadataHost,
    build_metadata_host,
    failed_shader,
)


def main() -> int:
    arguments = parse_arguments()
    client_root = arguments.client_root.resolve()
    output_path = arguments.output.resolve()
    cache_root = arguments.cache_root.resolve()

    if ctypes.sizeof(ctypes.c_void_p) != 8:
        raise RuntimeError("El host de Shaders.dll requiere Python de 64 bits")

    manifests = load_manifests(client_root / "Shaders")
    host_dir = build_metadata_host(
        TOOL_ROOT / "host" / "EngineMetadataStub.vcxproj",
        cache_root / "host",
        client_root / "Bin" / "Shaders.dll",
    )
    host = ShaderMetadataHost(host_dir)
    try:
        shaders = []
        for manifest in manifests:
            try:
                shaders.append(host.extract(manifest))
            except (AttributeError, OSError, RuntimeError) as error:
                shaders.append(failed_shader(manifest, error))
    finally:
        host.close()

    shaders.extend(
        load_internal_program_shaders(client_root / "src" / "Engine")
    )
    inventory = build_exact_runtime_inventory(
        shaders=shaders,
        shader_code_header=(
            client_root / "src" / "Engine" / "Graphics" / "ShaderCode.h"
        ),
        shader_source_root=client_root / "src" / "Shaders",
        runtime_catalog=load_runtime_catalog(
            client_root
            / "src"
            / "Engine"
            / "Graphics"
            / "DirectX12LegacyShaderFamily.cpp"
        ),
        include_bytecode=True,
    )
    entries = collect_entries(inventory)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_header(entries), encoding="ascii", newline="\n")
    print(
        f"Catalogo legacy generado: {len(entries)} fuentes en {output_path}",
        flush=True,
    )
    return 0


def collect_entries(inventory: dict[str, object]) -> list[dict[str, object]]:
    unique: dict[tuple[int, int, str], dict[str, object]] = {}
    hashes: dict[tuple[int, int], str] = {}
    for kind, collection in (
        ("vertex", inventory["vertex_variants"]),
        ("pixel", inventory["pixel_variants"]),
    ):
        for variant in collection:
            fingerprint = int(variant["runtime_source_fingerprint"], 16)
            source_size = int(variant["runtime_source_size"])
            bytecode_hex = str(variant["bytecode_hex"])
            hash_key = (fingerprint, source_size)
            previous = hashes.setdefault(hash_key, bytecode_hex)
            if previous != bytecode_hex:
                raise RuntimeError(
                    "Colision de fuente legacy con bytecode diferente: "
                    f"0x{fingerprint:016X}/{source_size}"
                )
            unique[(fingerprint, source_size, kind)] = {
                "fingerprint": fingerprint,
                "source_size": source_size,
                "kind": kind,
                "bytecode": bytes.fromhex(bytecode_hex),
            }
    return sorted(
        unique.values(),
        key=lambda item: (
            item["kind"],
            item["fingerprint"],
            item["source_size"],
        ),
    )


def render_header(entries: list[dict[str, object]]) -> str:
    lines = [
        "// Generated by scripts/generate-legacy-shader-bytecode.py. Do not edit.",
        "#ifndef SE_INCL_LEGACYD3D9SHADERBYTECODE_GENERATED_H",
        "#define SE_INCL_LEGACYD3D9SHADERBYTECODE_GENERATED_H",
        "",
    ]
    for index, entry in enumerate(entries):
        bytecode = entry["bytecode"]
        if len(bytecode) % 4:
            raise RuntimeError("El bytecode legacy no esta alineado a DWORD")
        lines.append(f"static const DWORD LEGACY_SHADER_BYTECODE_{index}[] = {{")
        words = [
            int.from_bytes(bytecode[offset : offset + 4], "little")
            for offset in range(0, len(bytecode), 4)
        ]
        for offset in range(0, len(words), 8):
            values = ", ".join(
                f"0x{value:08X}U" for value in words[offset : offset + 8]
            )
            lines.append(f"    {values},")
        lines.extend(("};", ""))

    lines.extend(
        (
            "static const LegacyD3D9ShaderBytecodeEntry "
            "LEGACY_SHADER_BYTECODE_CATALOG[] = {",
        )
    )
    for index, entry in enumerate(entries):
        kind = (
            "LegacyD3D9ShaderKind::Vertex"
            if entry["kind"] == "vertex"
            else "LegacyD3D9ShaderKind::Pixel"
        )
        lines.append(
            "    { "
            f"0x{entry['fingerprint']:016X}ULL, "
            f"{entry['source_size']}U, {kind}, "
            f"LEGACY_SHADER_BYTECODE_{index}, "
            f"sizeof(LEGACY_SHADER_BYTECODE_{index}) "
            "},"
        )
    lines.extend(
        (
            "};",
            "",
            "#endif",
            "",
        )
    )
    return "\n".join(lines)


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Genera el catalogo de bytecode D3D9 usado solo por los "
            "adaptadores de compatibilidad, sin compilacion durante el juego."
        )
    )
    parser.add_argument(
        "--client-root",
        type=Path,
        default=REPOSITORY_ROOT / "client",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=(
            REPOSITORY_ROOT
            / "client"
            / "src"
            / "Engine"
            / "Graphics"
            / "Generated"
            / "LegacyD3D9ShaderBytecode.h"
        ),
    )
    parser.add_argument(
        "--cache-root",
        type=Path,
        default=REPOSITORY_ROOT / ".itconfig" / "dx12-shader-inventory",
    )
    return parser.parse_args()


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, RuntimeError, ValueError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        raise SystemExit(1)
